### ISSUE TITLE
Match stats do not update

### ISSUE THREAD

**Issue by AzuuraD** [splewis/get5-web#10]
Creating a match works fine, the config gets sent to the server and works perfectly fine, however stats of the match when live and even after the match has finished do not show, forcing me to cancel before i set up another match on the server

http://i.imgur.com/JQRqoSV.jpg

**Comment by splewis** [comment]
That means the get5_apistats plugin can't send the HTTP requests to the web server.

I'm guessing Steamworks doesn't like trying to use an ip:port as the url. I don't know if there is a workaround (other than using a proper domain name), but I will look.

**Comment by AzuuraD** [comment]
I'll most likely be getting it put on a proper domain anyway

**Comment by splewis** [comment]
The SteamWorks library is wrapping [this http client](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/steam/isteamhttp.h#L31), and it looks like it requires a domain url (not a host:port) to be given. Omitting the port doing ``http://123.123.123.123`` *might* work if it's on port 80, but it's probably not worth doing that.

**Comment by AzuuraD** [comment]
That's fine,  I have the Web server set up on my domain now so all should be good.  Thanks for looking into it for me though :)
