### ISSUE TITLE
Forfeiting while ready up not tracked

### ISSUE THREAD

**Issue by tloesch** [splewis/get5-web#105]
Actual Behavior:
If the forfeit happens with get5_time_to_start while warmup, the match will not be marked as ended.

Expected Behavior:
If the forfeit happens with get5_time_to_start while warmup, the match should be marked as ended

**Comment by Technoblazed** [comment]
Going to assume you meant to make this over here: https://github.com/splewis/get5

**Comment by Technoblazed** [comment]
Judging by what you described, there needs to be a change ![here](https://github.com/splewis/get5/blob/master/scripting/get5.sp#L695) to trigger Get5_OnMapResult, updating the web client correct? (or something similar)

**Comment by tloesch** [comment]
i thought this is the right place because if i click at the cancel button from the match on the web ui i get following message:

{
  "message": "Match already finished"
}

So i thought get5 ends it well. But u are right it could be also a bug from get5.

I create now an issue at the get5 repo. Thanks

**Comment by tloesch** [comment]
@Technoblazed 

As you mentioned first, i created now an issue at the get-5 repo.
There i provided more information to the bug like repro steps and the debug log file.

Link: https://github.com/splewis/get5/issues/286
