### ISSUE TITLE
AH01630: client denied by server configuration

### ISSUE THREAD

**Issue by russh3l** [splewis/get5-web#106]
[Sun Aug 05 04:03:42.258364 2018] [authz_core:error] [pid 15732] [client ipadress:19185] AH01630: client denied by server configuration: /home/get5/get5-web-master/get5.wsgi, referer: http://domain

i made chmod 777 

any solution ?

**Comment by splewis** [comment]
https://wiki.apache.org/httpd/ClientDeniedByServerConfiguration
https://stackoverflow.com/questions/18392741/apache2-ah01630-client-denied-by-server-configuration

How to configure your webserver is mostly out-of-scope for this repository, unfortunately.
