### ISSUE TITLE
Either get5 or get5_apistats plugin missing

### ISSUE THREAD

**Issue by Muhamdmuaz** [splewis/get5-web#107]
Errors: get5_apistats.smx (Get5 Web API Integration): Required extension "SMJansson" file("smjansson.ext") not running L 08/31/2018 - 04:55:14: rcon from "43.245.207.224:13004": command "sm plugins list" Communications with routing cluster 'pww' restored.

**Comment by splewis** [comment]
Install [SMJansson](https://forums.alliedmods.net/showthread.php?t=184604). I guess the docs could be clearer.

That dependency may be removed pending https://github.com/splewis/get5/pull/294

**Comment by splewis** [comment]
https://github.com/splewis/get5/commit/d45a0ece783c780886ba27caaf6c8cf6b6074348

**Comment by mgjuhler** [comment]
Why is this not in the docs!?

**Comment by MikkelDK** [comment]
@mgjuhler read: [It's under readme!](https://github.com/splewis/get5#get5_apistats) 

`get5_apistats` is for integration with the `get5 web panel.` You **don't need** it unless you're using the `web panel`. **Note: you need the Steamworks extension for this plugin.** (If you are using get5 web panel!)

**Comment by splewis** [comment]
SMJansson isn't mentioned in the get5 docs at HEAd because get5 doesn't use SMJansson at HEAD.

Also, get5-web is pretty explicitly *experimental* and *not supported* so you really shouldn't be using it if you expect things to work.

**Comment by mgjuhler** [comment]
> @mgjuhler read: [It's under readme!](https://github.com/splewis/get5#get5_apistats)
> 
> `get5_apistats` is for integration with the `get5 web panel.` You **don't need** it unless you're using the `web panel`. **Note: you need the Steamworks extension for this plugin.** (If you are using get5 web panel!)

Do you read what I am complaining about? No where does it says that SMJansson is a requirement, it has previously been in the docs but has been removed. https://github.com/splewis/get5/pull/294/commits/2de6b83f3c3be93d9ba91729e88cf3c8d452daf8

**Comment by mgjuhler** [comment]
> @mgjuhler read: [It's under readme!](https://github.com/splewis/get5#get5_apistats)
> 
> `get5_apistats` is for integration with the `get5 web panel.` You **don't need** it unless you're using the `web panel`. **Note: you need the Steamworks extension for this plugin.** (If you are using get5 web panel!)

Do you read what I am complaining about? No where does it says that SMJansson is a requirement, it has previously been in the docs but has been removed. https://github.com/splewis/get5/pull/294/commits/2de6b83f3c3be93d9ba91729e88cf3c8d452daf8
