### ISSUE TITLE
Error reading get5_web_avaliable response

### ISSUE THREAD

**Issue by supaflybanzai** [splewis/get5-web#109]
when create match i have error "Error reading get5_web_avaliable response" where is the problem ?

**Comment by AserCSGO** [comment]
Check if your file is there.

**Comment by AserCSGO** [comment]
Did you install SteamWorks ?

**Comment by supaflybanzai** [comment]
yes i do, latest from
http://users.alliedmods.net/~kyles/builds/SteamWorks/

**Comment by supaflybanzai** [comment]
i dont have smjansson.ext.so, when i put it from https://github.com/thraaawn/SMJansson to extensions folder then its work.

**Comment by supaflybanzai** [comment]
Ok now its work fine. Problem was site address - bad configuration apache2 site.
