### ISSUE TITLE
Get request failed HTTP status code = 0

### ISSUE THREAD

**Issue by techlover1** [splewis/get5-web#11]
When I create a match (whether on your panel, or my self-hosted one) it gets stuck on match pending and in the server console I get this error: https://i.gyazo.com/69215d9458d469b1d8efae640f32b21c.png

Any help would be appreciated. Thanks

**Comment by splewis** [comment]
Not loading the match config (the error message from get5 itself, not the apistats plugin) is the bigger issue.

I'd suggest updating SteamWorks at least. And the plugin versions since I'm guessing your using old ones.

**Comment by techlover1** [comment]
I'm running SteamWorks 1.2.1 and get5 0.3.1

**Comment by splewis** [comment]
Steamworks isn't strictly versioned since it's just a wrapper on Valve's steam client. I'd suggest a build from http://users.alliedmods.net/~kyles/builds/SteamWorks/

**Comment by techlover1** [comment]
Using the latest builds of both get5 and SteamWorks results in the same error. https://i.gyazo.com/08d1f87329b1c676ce1f707f722c9749.png

**Comment by splewis** [comment]
Try using the get5_loadmatch_url command youself with the match url. (something like ``get5_loadmatch_url http://get5.splewis.net/match/12/config``

**Comment by techlover1** [comment]
Same error. Also the same if I store it with the .json extension on a webserver

**Comment by splewis** [comment]
Not much I can do then. My only suggestion would be to try updating the steam client on the server. There's one linked in the SteamWorks post: https://forums.alliedmods.net/showthread.php?t=229556

**Comment by techlover1** [comment]
Not sure if this is relevant but if I install system2 I get the error: `[get5.smx] Failed to load match config: Error receiving remote config via system2: Resolving timed out after 10515 milliseconds`
I'm working with KyleS in the SteamWorks thread over at alliedmods to try and get this sorted out. I'll keep you updated

**Comment by splewis** [comment]
Closing since it doesn't seem to be a get5-related issue and there's been no update.
