### ISSUE TITLE
Admin and Save team and players for admin

### ISSUE THREAD

**Issue by deziau** [splewis/get5-web#116]
Is it possible to make it so only one person has to make teams with players and it will be available to all the admin?

Also in the config every time i enable admin only the site doesn't work.

**Comment by splewis** [comment]
> Is it possible to make it so only one person has to make teams with players and it will be available to all the admin?

Yes, that is what the 'public team' option is for. It's only available for admins: https://github.com/splewis/get5-web/blob/master/get5/templates/team_create.html#L91

> Also in the config every time i enable admin only the site doesn't work.

Then there's a bug or you have it misconfigured. I can't tell you which one. The option works for me.

**Comment by deziau** [comment]
So i got the following things in my config and the staff that i want to use and one of them is my account as you see in the following pic;
https://imgur.com/a/FcHUWhD

But i am getting "Sorry, you don't have access to this webpanel" 

So what steam id do we put there and how is it meant to look like with multiple admin. If you can prove a pic or a format for it that would be great. 

Thank you

**Comment by deziau** [comment]
So i got admins to work: https://imgur.com/s9TkJq4
and i have checked if it on admin only by removing my id. 

But i still can not see the option to make the teams public.

**Comment by TandelK** [comment]
Problem solved. Issue was same Admins were added in Whitelist slot which should not be there
