### ISSUE TITLE
Wrong Matchconfig on BO2 with web panel.

### ISSUE THREAD

**Issue by asidani** [splewis/get5-web#123]
I installed Get5 and Get5 web panel correctly without any issues. Thanks for the nice installing industructions!
I'm only using BO2 on the server with pre vetoed maps, so i want to create a BO2 match with vetoes and only two maps to veto via web panel. When I start vetoing on the server, each Team can choose a map (works fine) but then only one team can choose a site (need both can choos) an after site pick, only ONE map is loading by the Get5. Get5 is crating a BO1.

**Comment by MikkelDK** [comment]
Get5 aka eBot? .. i don't think. ;)

**Comment by Technoblazed** [comment]
Post your issue here if it's related to eBot and not get5: https://github.com/deStrO/eBot-CSGO

**Comment by Technoblazed** [comment]
Please provide an example match config that's generated onto your server. Should be /csgo/remote_config.json or something similar.

**Comment by asidani** [comment]
`{
  "bo2_series": true, 
  "cvars": {
    "get5_web_api_url": "http://128.0.116.78/"
  }, 
  "maplist": [
    "de_cbble", 
    "de_inferno"
  ], 
  "match_title": "Map {MAPNUMBER} of {MAXMAPS}", 
  "matchid": "23", 
  "skip_veto": false, 
  "team1": {
    "flag": "DE", 
    "name": "Imperio eSports Trier", 
    "players": [
      "76561198141334523", 
      "76561198078165298", 
      "76561198110100254", 
      "76561198105737197", 
      "76561198234651728"
    ], 
    "tag": "T|IMP"
  }, 
  "team2": {
    "flag": "DE", 
    "name": "Ilmenau Himmelblau", 
    "players": [
      "76561198079171414", 
      "76561197974776555", 
      "76561198072319838", 
      "76561198142678521", 
      "76561198036254390", 
      "76561197965617607", 
      "76561198325661395", 
      "76561198040143960", 
      "76561198023018674"
    ], 
    "tag": "tui"
  }
}`

**Comment by splewis** [comment]
The match config looks fine, so it's (probably) a get5 plugin issue. Can you post the get5 version: https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version

**Comment by splewis** [comment]
Closing since there's no update here.
