### ISSUE TITLE
Possible to setup local web interface without sub-domain? 

### ISSUE THREAD

**Issue by swapnil2308** [splewis/get5-web#124]
![image](https://user-images.githubusercontent.com/13643744/50606828-1bebff80-0eed-11e9-8900-867c37232baa.png)

inside get5.conf
![image](https://user-images.githubusercontent.com/13643744/50606866-3c1bbe80-0eed-11e9-88e7-d9eed4af4c44.png)

need help to make a local web interface

**Comment by TandelK** [comment]
It is possible but you still require Internet connection to call API calls from Web Interface to Game Server

**Comment by Technoblazed** [comment]
Technically you don't on lan^

**Comment by TandelK** [comment]
oops didnt read the title

**Comment by swapnil2308** [comment]
If the game server and players are on lan and connection to the internet is
lost for a certain match. What is the stability?

**Comment by Technoblazed** [comment]
Game results won't be recorded to the web api if the gameserver can't reach the webserver. If you're on lan just run the webserver on lan.

**Comment by swapnil2308** [comment]
It is not able to detect get5 as a web folder,  I have shared the output
above.

I tried to installed it the same way as ebot for lan
Browser
IP_address/static
Shows root directory folders

**Comment by swapnil2308** [comment]
@Technoblazed @TandelK can anyone help?

**Comment by TandelK** [comment]
The thing is that Local LAN IPs wont work with this panel. You have to define a website hostname and than you can modify your Windows Host file to read to that host 

Can you let me know if the Panel and Game Server are on the same host or different. 

If they are different you can modify host file on the server to specially connect to that server using domain. 

For eg. webpanel address you set in apache2 is panel.gaming.com and enable the get5 conf to enable website and now on CSGO Server , you modify host file of the system with 

WebPanel IP : 192.168.1.100
CSGO Server IP : 192.168.1.103


So on game Server you need to modify this
Windows C:\Windows\system32\drivers\etc\hosts
192.168.1.100 panel.gaming.com

**Comment by swapnil2308** [comment]
> Any updates yet ?
was able to access web panel 
C:\Windows\system32\drivers\etc\hosts
LOCAL_IP_ADDRESS panel.gaming.com

**Comment by TandelK** [comment]
@Technoblazed Can you update the Installation Instructions with this method for using it on LAN.

**Comment by Technoblazed** [comment]
/etc/hosts
