### ISSUE TITLE
Cant find domain for get5

### ISSUE THREAD

**Issue by JealousDK** [splewis/get5-web#127]
![image](https://user-images.githubusercontent.com/13926280/51676761-e318e500-1fd7-11e9-9abf-95817543e392.png)
This is how my get5.conf looks like, but i cant seem to find the subdomain... Am i doing ServerName right?

**Comment by MikkelDK** [comment]
without <>

Example:
ServerName scrim.domainhere.tld
ServerAdmin email@domainhere.tld

;)

**Comment by Jargs** [comment]
https://i.imgur.com/zEXAxk3.png
https://i.imgur.com/aEYYE9r.png

Still not working!

**Comment by MikkelDK** [comment]
Did you make A-record scrim.domainhere.tld > IPaddress ? ;) 

And did you too create a "get5.wsgi"?

You can see howto: [INSTALL.MD](https://github.com/splewis/get5-web/blob/master/INSTALL.md#9-wsgi-configuration)

**Comment by Jargs** [comment]
https://i.imgur.com/UUsJuUO.png
https://i.imgur.com/22cLwzt.png

**Comment by MikkelDK** [comment]
/etc/init.d/apache2 restart and it should works. ;) 

If it don't - you need to make a A record point (scrim.domainhere.dk) > to the serverIPaddress.

**Comment by Jargs** [comment]
Maybe im asking stupid, but how do i make a A record point?

**Comment by MikkelDK** [comment]
via DNS records (from your hoster, where your homepage is located)

**Comment by Jargs** [comment]
https://i.imgur.com/lyZcze8.png
Like this right?

**Comment by Jargs** [comment]
Still not working... Do you have time for doing me some support on discord?

**Comment by Jargs** [comment]
Nevermind, it works now! Thx for the help mate +rep

**Comment by MikkelDK** [comment]
> https://i.imgur.com/lyZcze8.png
> Like this right?

Correct like that! ;) 
> Nevermind, it works now! Thx for the help mate +rep

No problemo! ;)
