### ISSUE TITLE
(bug?) Match result displays 16-15(Live)

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5-web#129]
(sorry for creating multiple issues)
Sometimes webpanel shows 16-15 score when  match ended 15-15.
[screenshot by player](https://user-images.githubusercontent.com/30292185/52184683-80d2a680-2859-11e9-8134-fe4f667344e2.jpg)
I changed end_time on DB manually,Is it bug or my config-bug?
thanks

http://get5.flowing.tokyo/match/90

**Comment by splewis** [comment]
It's probably a bug, but there's not enough information here to fix it. It's probably in get5 itself, anyway.

To diagnose the issue you should make sure the `get5_debug` cvar is set to `32`, then check ``addons/sourcemod/logs`` for get5_api debug logs.

That will show the API requests the get5_apistats plugin made. Knowing the get5 version would be needed as well.

**Comment by FlowingSPDG** [comment]
I'm so sorry,I found ```mp_overtime_enable 1```in live.cfg .
I thought it was disabled by my server.cfg ,,,sorry for taking your time.
it should be fixed now

**Comment by FlowingSPDG** [comment]
sorry it happens again even tho i set ``mp_overtime_enable 0``.
I'll send you log soon.
http://get5.flowing.tokyo/match/100

**Comment by FlowingSPDG** [comment]
I dont see problem for while,I have no idea why its not happening for now but probably it solved.
closing issue
