### ISSUE TITLE
Assertation Failed: pHost

### ISSUE THREAD

**Issue by AzuuraD** [splewis/get5-web#13]
when running a match, at halftime i get this error 9 times over in the server console,
`
httpclient.cpp (2374) : Assertion Failed: pHost && *pHost`

I also get the HTTP Status Code 0 between rounds
`L 08/04/2016 - 23:48:14: [get5_apistats.smx] ØàªØàª ;¨ ;¨
L 08/04/2016 - 23:48:14: [get5_apistats.smx] API request failed, HTTP status code = 0`
though i saw you're working on this anyway

**Comment by splewis** [comment]
What host is get5-web running on? Is there a proper domain for it, or just an ip:port?

**Comment by AzuuraD** [comment]
proper domain i have it hosted [here](get5.dale-jackson.co.uk)

**Comment by splewis** [comment]
Can you try setting ``get5_apistats_debug 32``, running a brief test, and pasting the results in the debug log at ``addons/sourcemod/logs/get5_apistats_debug.log``?

**Comment by AzuuraD** [comment]
Yeah I can get that done tomorrow morning for you

**Comment by AzuuraD** [comment]
I uploaded the log here https://www.dropbox.com/s/k6z9ru6kojoh4h6/get5_apistats_debug.log?dl=0

**Comment by splewis** [comment]
Thanks for getting the log file. I think I've found and reproduced the issue. Seems to be a change in how the core get5 plugin executed the cvars set a match config's ``cvar`` section.

**Comment by splewis** [comment]
This should be fixed by a change in the get5 plugin https://github.com/splewis/get5/commit/5c4a22421d11f47f24508dc24730e8696b280116. Updating it to that commit or past build 209+ should fix it.

**Comment by AzuuraD** [comment]
Awesome, thanks :)
