### ISSUE TITLE
Has anybody tried setting it up on windows?

### ISSUE THREAD

**Issue by BrianmSK** [splewis/get5-web#133]
Hey splewis or other people checking out this! Thanks for reading, my question is, is it possible to make this on windows and if so would anyone be so kind to help me set it up or just easily explain, In april im going to make a lan party and I wanted to use ebot but this seems more actual and less buggy and my last hope was pugsetup which is fine but this seems better, get5 installation is not really hard but this website is more complicating for me sadly thanks for any answer

**Comment by TandelK** [comment]
you can use Windows 10 Bash Tool with Ubuntu download from Windows Store . I Helped one of the guy for starting it in Windows 10 using Ubuntu via Windows Store.

**Comment by Technoblazed** [comment]
If you don't wanna do ^, as long as you can figure out how to install apache/nginx with the flask requirements you should be fine, I'm sure if you google enough you'll find it.

**Comment by BrianmSK** [comment]
> you can use Windows 10 Bash Tool with Ubuntu download from Windows Store . I Helped one of the guy for starting it in Windows 10 using Ubuntu via Windows Store.
> 
> Download Ubuntu for Windows 10 : https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6

Thanks, I´m going with this option, if I have any troubles can I contact you? If so where?

**Comment by BrianmSK** [comment]
Eh, through the windows bash Ubuntu I was not able to install mysql server i just got errors I couldnt resolve, tried many sites with errors, im struggling really but i want the web very much

**Comment by BrianmSK** [comment]
> you can use Windows 10 Bash Tool with Ubuntu download from Windows Store . I Helped one of the guy for starting it in Windows 10 using Ubuntu via Windows Store.
> 
> Download Ubuntu for Windows 10 : https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6

thanks for help, its working but i cant manage mysql to get working i just get errors and errors, other steps are working fine

**Comment by TandelK** [comment]
Yeah just require the Port setup correctly on Windows side.  Are you trying to use localhost for the connection of the database ?  Try to use the IP Instead of localhost like 127.0.0.1 and start the server.

**Comment by BrianmSK** [comment]
Sorry its all messed up here, i figured now the mysql but when i try to do step 7 database migration i get error (1045, "Access denied for user 'get5'@'localhost' (using password: YES)") every other step was done and when i type localhost or 127.0.0.1 i get apache2 default ubuntu page, sorry for the troubles, im not really big guy into these things but i want to get it working, thanks for the help really!

**Comment by TandelK** [comment]
Add me on Steam / Discord i will help you out completely.

**Comment by BrianmSK** [comment]
can you give me your discord id? :)

**Comment by TandelK** [comment]
> can you give me your discord id? :)

TandelK#7676

**Comment by TandelK** [comment]
We did make the panel work with Ubuntu Bash for Windows 10. We have not working panel on LAN Server also with this having Web Server (Game Panel) and CSGO Server on the same system and they are communicating perfectly . A minor workaround with host file is required for setting it up properly with Fixed IPs on the network.

**Comment by Technoblazed** [comment]
Maybe I should setup a docker instance of this lol

**Comment by TandelK** [comment]
yeah but i think many people will find this useful except for me where i have almost no knowledge of docker deployment lol . Am i a the only one
