### ISSUE TITLE
No match stats in web panel

### ISSUE THREAD

**Issue by SGTshan** [splewis/get5-web#134]
Creating a match and loading the config via the web panel works fine. Just the stats won't show up in the panel, without any errors in the debug or sourcemod log. What I really don't understand is, that it's perfectly working in the demo web panel (https://get5.splewis.net/). Stats are updating etc. But why does it not work in my own web panel? What could fix my problem?

**Comment by TandelK** [comment]
Can you drop us your Webpanel address to check ?

**Comment by SGTshan** [comment]
**[Here](https://smg.classiccomp.tk)**

**Comment by TandelK** [comment]
i can see that server is not sending report back as the match has not yet started as per the Status is pending

**Comment by SGTshan** [comment]
What could be the reason for that? As I wrote: When I use the demo panel all things are working fine.

**Comment by splewis** [comment]
> errors in the debug or sourcemod log.

I'm not sure what logs you mean there.

You should be checking:
- addons/sourcemod/logs for error logs
- wherever your web server logs are /var/log/apache2 probably?

**Comment by TandelK** [comment]
@SGTshan any logs you can provide us ?  By uploading them to pastebin and you can give us link and we can check out for any error logs and help you out.

**Comment by SGTshan** [comment]
I've found an issue with my apache. It was not listening for requests on the right ip adress, this is now fixed but stats are still not working. Sourcemod and Apache logs have no further errors in it.

**Comment by SGTshan** [comment]
Does anyone have an solution?
I only get this error from the `pyflakes *.py` command:

`match_test.py:105: redefinition of unused 'test_match_create_not_my_server' from line 46`

I also ran the test.sh and it gave me no errors.

**Comment by SGTshan** [comment]
Here is my apache2 error log:

`[Sat Mar 02 00:00:22.545248 2019] [mpm_prefork:notice] [pid 12751] AH00163: Apache/2.4.34 (Ubuntu) OpenSSL/1.1.1b mod_wsgi/4.5.17 Python/2.7 configured -- resuming normal operations
[Sat Mar 02 00:00:22.545310 2019] [core:notice] [pid 12751] AH00094: Command line: '/usr/sbin/apache2'
--------------------------------------------------------------------------------
INFO in match [/var/www/get5-web/get5/match.py:195]:
User 1 created match 3, assigned to server 1
--------------------------------------------------------------------------------
[Sat Mar 02 11:54:28.105207 2019] [wsgi:error] [pid 20202] [client 95.91.252.3:1109] INFO:get5:User 1 created match 3, assigned to server 1, referer: https://smg.classiccomp.tk/match/create
--------------------------------------------------------------------------------
INFO in match [/var/www/get5-web/get5/match.py:195]:
User 1 created match 4, assigned to server 1
--------------------------------------------------------------------------------
[Sat Mar 02 11:56:22.819219 2019] [wsgi:error] [pid 20199] [client 95.91.252.3:1103] INFO:get5:User 1 created match 4, assigned to server 1, referer: https://smg.classiccomp.tk/match/create
`

**Comment by TandelK** [comment]
Can you run the panel on http instead of https ?

**Comment by SGTshan** [comment]
Thank you very much @TandelK :)

My apache was configured to redirect all request from http to https, that was the error. Thanks!

**Comment by superdaN12** [comment]
@SGTshan  How you fixed it in detail? :)

**Comment by TandelK** [comment]
@superdaN12 Just remove http to https redirect and run Web Panel on http instead of https because SteamWorks does not work properly with HTTPS as of now.
