### ISSUE TITLE
Add an admin section to the panel

### ISSUE THREAD

**Issue by moshe86** [splewis/get5-web#135]
Logging into the administration panel of teams, servers, etc. ... It should only be done by designated persons.
In this panel everyone who logs in with steam can access the administration.
If you can add such a function where we can select which steam id to have access to this panel.

**Comment by splewis** [comment]
Sorry, this isn't something I'm going to add.

**Comment by TandelK** [comment]
@moshe86 If you want to restrict the panel  to specific people make sure to keep 1 extra steam id that can be added as Whitelisted Person and other main admins IDs in Admins Section. That way you can keep restricted to certain people. The people in Whitelisted section and Admins section can only access the panel.

**Comment by moshe86** [comment]
@TandelK First of all I want to thank you for your involvement and you have answered my question.
I tried to add a few steam ids in the prod_config.py file to admin but do not follow these changes ...
E.g:

# You may set the server to allow the whitelisted steam to login.
# By default, any user can login and create teams / servers / matches.
WHITELISTED_IDS = [
'STEAM_1: 1: 213 603 204'
'STEAM_1: 1: 32,768,300'
'STEAM_0: 1: 70,406,486'
]

# Admins will have extra access to create "public" teams, and if ADMINS_ACCESS_ALL_MATCHES
# is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match.
ADMIN_IDS = [
'STEAM_1: 1: 213 603 204'
]

If I miss something or wrong, please explain to me how to fix this problem.

Thank you again

**Comment by TandelK** [comment]
Its my mistake i forgot to mention you to use STEAMID64 (Dec) Format

For eg : My Steam ID is ktandel5151
ADMIN_IDS = [
'76561198112911540',
]

Always put , after any id you put even if it is ending , follow same type used in Map List of Prod_config and after you update it once make sure to do db upgrade command

**Comment by moshe86** [comment]
I did all these steps but I have the same problem ...
Anyone can login with steam id in the panel and can administer servers, teams, etc ... Full access
I also attached an image showing how the prod_config.py file is configured and the message after db upgrade "./manager.py db upgrade"
![get5](https://user-images.githubusercontent.com/47644360/53162792-76dcd180-35d5-11e9-8088-7b8b114fff3d.PNG)

**Comment by TandelK** [comment]
activate venv first
