### ISSUE TITLE
Isssue with fresh Installation alembic setup

### ISSUE THREAD

**Issue by TandelK** [splewis/get5-web#136]
Recently i went to create fresh installation of this panel on Ubuntu 16.04 and found this issue that it does not push prod_config things to database at all.

```
(venv) root@ubnt:/var/www/get5-web# ./manager.py db upgrade
/var/www/get5-web/venv/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py:2513: Warning: '@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead
  cursor.execute('SELECT @@tx_isolation')
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> d1a12773d8f3, empty message
INFO  [alembic.runtime.migration] Running upgrade d1a12773d8f3 -> 54c17052c8f4, empty message
INFO  [alembic.runtime.migration] Running upgrade 54c17052c8f4 -> c18a8e939c8e, empty message
INFO  [alembic.runtime.migration] Running upgrade c18a8e939c8e -> 8bc3fc909d1a, empty message
INFO  [alembic.runtime.migration] Running upgrade 8bc3fc909d1a -> 5b607892c512, empty message
INFO  [alembic.runtime.migration] Running upgrade 5b607892c512 -> d84462b5a7a5, empty message
INFO  [alembic.runtime.migration] Running upgrade d84462b5a7a5 -> e0e6530b2ce4, empty message
INFO  [alembic.runtime.migration] Running upgrade e0e6530b2ce4 -> 2610b84c0bf5, empty message
INFO  [alembic.runtime.migration] Running upgrade 2610b84c0bf5 -> cca93c217647, empty message
INFO  [alembic.runtime.migration] Running upgrade cca93c217647 -> 48c5a5bb98cf, empty message
INFO  [alembic.runtime.migration] Running upgrade 48c5a5bb98cf -> b28b5677726e, empty message
(venv) root@ubnt:/var/www/get5-web#
```
This can be called duplicate Issue which is of #134 & #135 adding of Admin in SQL does not work

The reason why it is not getting users and match stats is all in this

**Comment by TandelK** [comment]
@splewis @Technoblazed   any ideas for this issue?

**Comment by Technoblazed** [comment]
What's the issue here exactly?

**Comment by TandelK** [comment]
Migrations not posting updates when used ./manager.py db upgrade

**Comment by TandelK** [comment]
@Technoblazed what i actually tried is to setup Whitelisted IDs and Admins ID . When i used prod_config.py and did a ./manager.py db upgrade the database are not getting updated. Whitelisted IDs are not working , everyone is able to sign in even though they are perfectly added in prod_config.py

**Comment by Technoblazed** [comment]
@TandelK, can you show me an example of your prod config with the sensitive stuff commented out

**Comment by TandelK** [comment]
##### You must change these before running
SQLALCHEMY_DATABASE_URI = 'mysql://user:password@localhost/db'  # Sqlalchemy database connection info
STEAM_API_KEY = ''  # See https://steamcommunity.com/dev/apikey
SECRET_KEY = 'justcheck'  # Secret key used for flask cookies

##### Everything below this line is optional to change

import os

location = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__), '..', 'logs'))
LOG_PATH = os.path.join(location, 'get5.log')

DEBUG = False
TESTING = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
USER_MAX_SERVERS = 10  # Max servers a user can create
USER_MAX_TEAMS = 100  # Max teams a user can create
USER_MAX_MATCHES = 1000  # Max matches a user can create
DEFAULT_PAGE = '/matches'
ADMINS_ACCESS_ALL_MATCHES = True  # Whether admins can always access any match admin panel
CREATE_MATCH_TITLE_TEXT = False # Whether settings for "match title text" and "team text" appear on "create a match page"

# All maps that are selectable in the "create a match" page
MAPLIST = [
    'de_cache',
    'de_cbble',
    'de_inferno',
    'de_mirage',
    'de_nuke',
    'de_overpass',
    'de_train',
    'de_dust2',
    'de_season',
]

# Maps whose checkbox is selected (in the mappool) by default in the "create a match" page
DEFAULT_MAPLIST = [
    'de_cache',
    'de_dust2',
    'de_inferno',
    'de_mirage',
    'de_nuke',
    'de_overpass',
    'de_train',
]

# You may set the server to allow allow whitelisted steamids to login.
# By default any user can login and create teams/servers/matches.
WHITELISTED_IDS = [
"7656119xx",
"7656119xx",
]

# Admins will have extra access to create "public" teams, and if ADMINS_ACCESS_ALL_MATCHES
# is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match.
ADMIN_IDS = [
"765611981xx",
"765611983xx",
]

**Comment by Technoblazed** [comment]
Do you want to add me on Discord so we can talk about this? Techno#0001

**Comment by TandelK** [comment]
Sure

**Comment by Technoblazed** [comment]
Fixed in https://github.com/splewis/get5-web/pull/138

**Comment by TandelK** [comment]
Thanks @Technoblazed .
