### ISSUE TITLE
mp_overtime_enable 1 if match is BO2,3or more

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5-web#139]
that mp_overtime is still 0 even if match config is bo2+.

**Comment by TandelK** [comment]
can you check properly your cfg/get5/live.cfg about this settings . it has nothing to do with BO2 or BO3. Everytime a new map start live.cfg is executed automatically forcing mp_overtime to be enabled.

**Comment by TandelK** [comment]
I tried to replicate this whole issue on my testing server and with BO3 there was no issue as soon as Second Map was 15-15 there was Overtime 1 came. Seems to be some kind of plugin or config modifying your mp_overtime_enable command. Please check it once more.

**Comment by FlowingSPDG** [comment]
Thanks for reply.
I've checked my live.cfg and there's ```mp_overtime_enable 0```.Sorry about it.
So,there's another question.
Can I toggle OT option by webpanel?
I'm running league with that webpanel,but some tiers should have BO1 w/o OT,and some others are BO2 WITH OT.

**Comment by TandelK** [comment]
There is no option as of now in WebPanel but after you start the match you can send a command via rcon of webpanel manually to disable overtime.

**Comment by FlowingSPDG** [comment]
(sorry for late res)
hmm okay,but I wanna do that w/o admin's operation.
for my league,All player should create match by theirself.(all teams are public_team 1)
so any possibility to do it automatically?

**Comment by TandelK** [comment]
We cannot do it via this panel but you can modify the panel as per your requirement.
