### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by sklafg** [splewis/get5-web#140]
Ich can't login with steam because my name has special characters. Also on the stats page my name don't appear. 
My name has characters like  ¢ , ε and µ .

**Comment by TandelK** [comment]
it is already mentioned everywhere on the guide that the database wont accept this kind of symbols while saving it. It is not recommend to use this type of Steam Name.

**Comment by splewis** [comment]
I'm sure there's somewhere the charset or encoding options just need to be changed. I have no intention to figure out what to change, though. Pull requests welcome.

**Comment by splewis** [comment]
Also #101
