### ISSUE TITLE
Creating new columns in database

### ISSUE THREAD

**Issue by PhlexPlexico** [splewis/get5-web#142]
Hi,

I was wondering how exactly to go about updating some of the tables during a manager db upgrade? I'm trying to dig around and lookup Alembic, but cannot find a way to alter a table to add a column. Is there a go-to reference that I can find, especially in refernce to this project?

Thanks!

**Comment by TandelK** [comment]
By default when you run db upgrade command it just creates table in the database .  If you are looking forward to know the data of admins data in users table they will get created when first login of each and every admin. If whitelisted that will be also created when they do first time login. 

https://github.com/splewis/get5-web/tree/master/migrations/versions is where all the database creation is added.

**Comment by PhlexPlexico** [comment]
Oh my goodness, you're a saviour. Thank you! Was attempting to look for it so I can add in my own columns for this. Thank you very much for the quick response!
