### ISSUE TITLE
Putting Vertigo on the online match creation screen

### ISSUE THREAD

**Issue by SquidThePrinter** [splewis/get5-web#143]
As per the [update from 3/28](https://blog.counter-strike.net/index.php/category/updates/), Vertigo has replaced Cache in Active Duty. Any chance that we can get it placed on the match creation screen and default to on?

**Comment by TandelK** [comment]
You can easily modify that by yourself and update update in this repo in file of prod_config.py located in instance.

**Comment by TandelK** [comment]
https://github.com/splewis/get5-web/pull/144 . 

Created a Pull Request and should be done once splewis update and allow the Changes in github

**Comment by splewis** [comment]
It's a config file for a reason. You can put whatever you want in it.
