### ISSUE TITLE
no connection from get5.splewis.net to server with error [get5.smx] json_decode: expected key string at 75   [get5.smx] Failed to load match config: invalid match json

### ISSUE THREAD

**Issue by Fortage** [splewis/get5-web#147]
when i create match on https://get5.splewis.net/ match create but not used on server with error 
{"available":1,"gamestate":0,"avaliable":1,"plugin_version":"0.7.1+458"}
L 04/10/2019 - 04:04:30: [get5.smx] json_decode: expected key string at 75
L 04/10/2019 - 04:04:30: [get5.smx] Failed to load match config: invalid match json
how me fix it? 
If i write on console get5_loadmatch_url https://get5.splewis.net/match/2328
i see this error
L 04/10/2019 - 04:07:31: [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0

**Comment by PhlexPlexico** [comment]
This is more of a get5 bug, and not a get5-web bug. Also, did you install all the required dependencies for get5, that are listed in the README in that repository?

**Comment by Fortage** [comment]
Yes, i install Steamworks, SMjansson, soursemod, metamod, get5, all in works. Get5 work in server. Get5_apistats work, When i used sm plugins list, i don't have errors.

**Comment by PhlexPlexico** [comment]
Are you using the latest development build? What if you try the release build on the get5 releases?

**Comment by Fortage** [comment]
yes, i download latest build from https://ci.splewis.net/job/get5/lastSuccessfulBuild/ .  
hmm, this is very strange, with version 0.7.1 https://github.com/splewis/get5/releases/tag/0.7.1 it all worked. ty
