### ISSUE TITLE
 The mysql base "get5" is deleted automatically

### ISSUE THREAD

**Issue by Fortage** [splewis/get5-web#161]
When I installed get5-web, everything worked for me. After that, every 2 weeks the error "Sorry, unexpected error: (_mysql_exceptions.OperationalError) (1049," Unknown database 'get5' ") (Background on this error at: http://sqlalche.me/e/e3q8)" appears that There is no get5 base. Indeed, there is no get5 database in mysql. We have to create a database get5 and write tables into it. And this situation every 2 weeks.

**Comment by splewis** [comment]
Sorry, there is nothing in this code that will delete your database, your issue is elsewhere.
