### ISSUE TITLE
Sorry, unexpected error: 'GET5_URL_OVERRIDE'

### ISSUE THREAD

**Issue by JacquesGarre** [splewis/get5-web#183]
Hi,

First, thank you very much for your awesome work. 

I get an error after creating a match : Sorry, unexpected error: 'GET5_URL_OVERRIDE'

The match still gets created and saved.I don't know if it's related to that, but once we join the csgo server, the match doesn't set up or anything. The loaded config is the default server config, we can't type !ready or anything. Could you please help us? 

Thanks!

**Comment by splewis** [comment]
Did you set a `GET5_URL_OVERRIDE` in your config file? (https://github.com/splewis/get5-web/blob/master/instance/prod_config.py.default#L68)

What version are you using?

**Comment by JacquesGarre** [comment]
Hi man, thank you for your answer,
I didn't set one, do I have to set it to my subdomain name? like http://subdomain.domain.com ?
I'm using get5-web on the master-branch (https://github.com/splewis/get5-web)
I have to check about the python version I'm using

**Comment by miroxmaro** [comment]
Hi,

I have this same problem and I can't solve it.
What type of URL i must enter in GET5_URL_OVERRIDE in the config file? Domain/Server IP/Subdomain? I tried everything and it still not working.

Thanks for answer!
