### ISSUE TITLE
I need help with installation

### ISSUE THREAD

**Issue by FPSGuilherme** [splewis/get5-web#186]
I did the complete installation and everything is working, I would like to know if you can activate an SSL certificate for the website?

**Comment by TandelK** [comment]
The panel will only show stats via HTTPS (SSL) but cannot send API request through HTTPS to game Servers due to issues with SteamWorks only supporting HTTP right now. So you can do one thing for public you can give SSL version for showing Stats but for Admins use HTTP for creating matches .

**Comment by FPSGuilherme** [comment]
Ok

> O painel mostrará apenas estatísticas via HTTPS (SSL), mas não poderá enviar solicitações de API através de HTTPS aos servidores de jogos devido a problemas com o SteamWorks que suporta apenas HTTP no momento. Assim, você pode fazer uma coisa para o público, pode fornecer a versão SSL para mostrar estatísticas, mas para os administradores usar HTTP para criar correspondências.
