### ISSUE TITLE
httpclient assertion failed

### ISSUE THREAD

**Issue by toomuchio** [splewis/get5-web#22]
Saw this issue opened and closed a few times yet to be resolved.

https://github.com/splewis/get5-web/issues/11
https://github.com/splewis/get5-web/issues/6

Not sure what the issue is, latest Ubuntu LTS total fresh install of the server and all underlying plugins and extensions. Just spun the VM up today, more than happy to give out temporary ssh to debug. I'll be attempting to debug it myself. But before I do has anybody resolved this already? Is there a working solution?

> get5_loadmatch_url get5.splewis.net/match/12/config
> httpclient.cpp (2374) : Assertion Failed: pHost && *pHost
> L 09/24/2016 - 15:18:37: [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0
> L 09/24/2016 - 15:18:37: get5_event: {
>     "params": {
>         "path": "Steamworks GET request failed, HTTP status code = 0"
>     },
>     "matchid": "",
>     "event": "match_config_load_fail"
> }
> L 09/24/2016 - 15:18:37: {
>     "params": {
>         "path": "Steamworks GET request failed, HTTP status code = 0"
>     },
>     "matchid": "",
>     "event": "match_config_load_fail"
> }
> L 09/24/2016 - 15:18:37: [get5_logger.smx] Get5_OnLoadMatchConfigFailed: Steamworks GET request failed, HTTP status code = 0

**Comment by toomuchio** [comment]
Was able to resolve this by compiling system2 myself, maybe there was a dependency missing on the base install of Ubuntu. And get5-web was running on the same server as my CS servers and nat loopback wasn't working so I had to fix that as well.

Still getting some asserts though I think it's due to when logos are empty, doesn't seem like it breaks the plugins though.

> L 09/24/2016 - 18:58:52: [get5_logger.smx] Get5_OnGameStateChanged: 0 -> 1
L 09/24/2016 - 18:58:52: get5_event: {
    "params": {
        "team1_name": "ZEN One",
        "team2_name": "ZEN Two"
    },
    "matchid": "8",
    "event": "series_start"
}
L 09/24/2016 - 18:58:52: {
    "params": {
        "team1_name": "ZEN One",
        "team2_name": "ZEN Two"
    },
    "matchid": "8",
    "event": "series_start"
}
L 09/24/2016 - 18:58:52: [get5_logger.smx] Get5_OnSeriesInit
httpclient.cpp (2374) : Assertion Failed: pHost && *pHost
Assert( Assertion Failed: pHost && *pHost ):httpclient.cpp:2374

httpclient.cpp (2374) : Assertion Failed: pHost && *pHost
L 09/24/2016 - 18:58:52: World triggered "Round_Start"
assert_20160924185852_9.dmp[94912]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160924185852_9.dmp
L 09/24/2016 - 18:58:52: server_cvar: "sm_nextmap" "de_train"
L 09/24/2016 - 18:58:52: server_cvar: "sv_alltalk" "1"
L 09/24/2016 - 18:58:52: server_cvar: "sv_competitive_official_5v5" "1"
L 09/24/2016 - 18:58:52: server_cvar: "sv_deadtalk" "1"
L 09/24/2016 - 18:58:52: [get5_mysqlstats.smx] Starting match id 4
L 09/24/2016 - 18:58:52: [get5_apistats.smx] API request failed, HTTP status code = 0
L 09/24/2016 - 18:58:52: [get5_apistats.smx] ▒p
                                               L 09/24/2016 - 18:58:52: [get5_apistats.smx] Logo request failed, status code = 0
L 09/24/2016 - 18:58:52: [get5_apistats.smx] API request failed, HTTP status code = 0
L 09/24/2016 - 18:58:52: [get5_apistats.smx] ▒p
                                               L 09/24/2016 - 18:58:52: [get5_apistats.smx] Logo request failed, status code = 0
L 09/24/2016 - 18:58:52: "***<2><*****><>" STEAM USERID validated
assert_20160924185852_9.dmp[94912]: Finished uploading minidump (out-of-process): success = yes
assert_20160924185852_9.dmp[94912]: response: Discarded=1
assert_20160924185852_9.dmp[94912]: file ''/tmp/dumps/assert_20160924185852_9.dmp'', upload yes: ''Discarded=1''
PutClientInServer: no info_player_start on level

**Comment by splewis** [comment]
Yes, there was a bug trying to download empty logos (fixed https://github.com/splewis/get5/commit/a910566ad78ef892ea29f281e8dd69444fe6a569).

Hopefully your issues are fixed now? Steamworks has some limitations when sending HTTP requests. I should try to update the readme with some of those notes.

**Comment by toomuchio** [comment]
All resolved yeah I figured that was a bug with logos I was going to send a pull request but I never got round to it, same fix I used.

All issues resolved I think those other guys may have been running their web servers locally and having issues with NAT loopback like myself might be worth putting in the README to remember to fix that on your router or stick a static entry into /etc/hosts like I did.

I did have issues with Steamworks as well after that I'm not sure why System2 works a lot better, but the build from the forums is really out of date. If you want to build your own copy the Makefile needs to be amended -I$(SMSDK)/public/sourcepawn is the incorrect path for the header files since 1.9. I think making it clear that System2 is the better option is probably a good idea :)

**Comment by splewis** [comment]
It's not really a better option if using the get5_apistats plugin (aka using this webpanel) since it can only use SteamWorks.

system2 is just an alternative for the get5_loadmatch_url command.

**Comment by toomuchio** [comment]
Ah I see makes sense.

**Comment by Technoblazed** [comment]
Resolved in latest patches

**Comment by splewis** [comment]
Speculatively closing since we believe this is fixed.
