### ISSUE TITLE
Cancel match error

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5-web#27]
When viewing a match from the admin panel, clicking the "Cancel match" button from the drop down menu seems to kill the system and not correctly stop the match. Will look into more information for you.

**Comment by splewis** [comment]
What do you mean by "kill the system"? Crash the web server?

**Comment by Technoblazed** [comment]
It sort of hangs, not so far as crashes, but continues to think the  server is in use etc, like the match does not correctly end.

**Comment by Technoblazed** [comment]
I can't repeat this so must've been on my end :D
