### ISSUE TITLE
Debian 7.0 Installation

### ISSUE THREAD

**Issue by AFreeman94** [splewis/get5-web#3]
ERROR: get5.api_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: get5.api_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/get5-web/get5/__init__.py", line 6, in <module>
    import steamid
  File "/home/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id

Even with the requirements.txt loading successfully. Its on  debian 7 server. If you could provide insight that would be awesome as I had someone here at the Datacenter install it and tell me there may be a bug in the install

**Comment by splewis** [comment]
That means the [python-valve](https://pypi.python.org/pypi/python-valve/0.1.1) package was not installed. The requirements.txt file contains it, and the tests pass on the travis CI tests now when they are installed in a virtualenv.

**Comment by AFreeman94** [comment]
We are still recieving errors, if there is any chance you could help us find a solution to our problems please message me on steam at http://steamcommunity.com/id/Freemancode

**Comment by trinialol** [comment]
Hello, everything seems to work now, except that we can't reach the website yet.

This is how it looks in the console: http://puu.sh/pANd8/3c00470463.png

So, how can we reach the website now? I cloned the git-folder in /var/www ofc. so the path to it is /var/www/get5-web.

**Comment by splewis** [comment]
@AFreeman94 

I usually don't add people on steam. 

@trinialol 

You should make a separate issue - but you should configure a production web server (e.g. apache2 using these instructions: http://flask.pocoo.org/docs/0.11/deploying/mod_wsgi/) rather than the built-in flask server that is meant for testing/development.

**Comment by trinialol** [comment]
I just installed all the packages, which it asked for. So basically I installed that valve-package, and after that it asked me for all Flask-Packages. After I installed all of them, it worked.

**Comment by trinialol** [comment]
Hello again, so I just setted up wsgi with apache. Now we get an internal Server Error 500: http://mm.marxmengaming.com

Config-File looks like that:

<VirtualHost *:80>
    ServerName mm.marxmengaming.com

    WSGIDaemonProcess get5 user=user group=group threads=5
    WSGIScriptAlias / /var/www/get5-web/get5.wsgi

    <Directory /var/www/get5-web>
        WSGIProcessGroup get5
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from ally
    </Directory>
</VirtualHost>

PS: Ofcourse I changed user and group correctly.

**Comment by splewis** [comment]
Check the Apache error logs. Should be in /var/log/apache2 in error.log

**Comment by AFreeman94** [comment]
IOError: [Errno 13] Permission denied: '/var/www/get5-web/logs/get5.log'
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###] mod_wsgi (pid=6759): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###] mod_wsgi (pid=6759): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###] Traceback (most recent call last):
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]     from get5 import app as application
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]   File "/var/www/get5-web/get5/__init__.py", line 39, in <module>
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]     app.config['LOG_PATH'], when='midnight')
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]   File "/usr/lib/python2.7/logging/handlers.py", line 170, in __init__
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]   File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]     StreamHandler.__init__(self, self._open())
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]   File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
[Wed Jun 22 13:39:26 2016] [error] [client ##.##.###.###]     stream = open(self.baseFilename, self.mode)

**Comment by splewis** [comment]
Did you change the ownership of the logs directory?

https://github.com/splewis/get5-web#deployed-using-apache2-with-mod_wsgi

You can also disable (the possibly broken) logging by removing the LOG_PATH variable from your instance/prod_config.py file.

**Comment by trinialol** [comment]
It was just about the permissions, lmao. It's working now. :)

**Comment by D0peX** [comment]
@trinialol Hi, Can you tell me what issue you had with the perms? Thanks

**Comment by trinialol** [comment]
It also needed 777 permissions on the most files, except for the config-files. I gave them 644.

**Comment by splewis** [comment]
FYI: I only today removed the hardcoded references to the website being run on my domain (get5.splewis.net), so you would want to update (git pull) for that update. Dropping the database tables and running ``./manager.py db upgrade`` should work. (dropping the tables would only be required this time, in the future just the upgrade command would be sufficient)
