### ISSUE TITLE
Having issues deleting Teams

### ISSUE THREAD

**Issue by TandelK** [splewis/get5-web#30]
I have been trying to delete in the panel. This is the error i am getting for mysql exception. 

Sorry, unexpected error: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`clanpanel`.`match`, CONSTRAINT `match_ibfk_3` FOREIGN KEY (`team2_id`) REFERENCES `team` (`id`))') [SQL: u'DELETE FROM team WHERE team.id = %s'] [parameters: (2,)]

**Comment by splewis** [comment]
Can you provide any version info? Usually the commit will be displayed in the footer.

**Comment by Technoblazed** [comment]
@splewis I get this on the latest version, seems to be an issue where there's matches present that a team has played. --> if a team has match history, you can't delete.

**Comment by splewis** [comment]
It's mostly intended that you can't delete teams once they've been used in a match, but it's supposed to not show the button and not display stack traces.

**Comment by TandelK** [comment]
I was able to delete everything via SQL Access.
