### ISSUE TITLE
Errno 13 - Cannot add server

### ISSUE THREAD

**Issue by DigitalFriends** [splewis/get5-web#31]
I get "Sorry, unexpected error: [Errno 13] Permission denied" when trying to add a new server to my get5-web installation.

**Comment by splewis** [comment]
There's much I can do with that information. Are you able to get any error logs? If using apache they are usually at ``/var/log/apache2/error.log``.

Otherwise there might be useful information at where get5 was installed in the ``logs``, but that's less likely to be useful.

**Comment by splewis** [comment]
Closing from no information. Feel free to reopen if you have any new information.
