### ISSUE TITLE
problems with installation.

### ISSUE THREAD

**Issue by MikkelDK** [splewis/get5-web#34]
What can i do for fixing this error? :)

 sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-fbqCr8/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-fbqCr8/MySQL-python/setup.py", line 17, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found

**Comment by Technoblazed** [comment]
Installation instructions are extremely basic, but you could've just googled it:

```
apt-get install libmysqlclient-dev
```

**Comment by MikkelDK** [comment]
Oh rofl, i didnt know haha! 👍 

Are it's correctly I needed to edit match.cfg for each time i need to play match for using get5?

Example: BO3 VETO?

**Comment by splewis** [comment]
The point of this web interface is that it sends the match config (which can be named whatever you want, there is no "match.cfg") to the game server, so you don't ever have to edit files.

**Comment by MikkelDK** [comment]
Hmm i have try used the Web site for test. But can't see how it works. Or about it's need to fill matchid?

**Comment by Technoblazed** [comment]
@MikkelDK You don't need to edit any files for that, the webpanel will automatically set the matchid to the next id in the database.

**Comment by MikkelDK** [comment]
Thanks @Technoblazed & @splewis for the pretty good info.

I have found one problem.

(if i adding 
ADMIN_IDS
(mysteamid64here)

And type: ./manager.py db upgrade
(Error/problem: ImportError: No module named valve.steam.id < what todo)

**Comment by Technoblazed** [comment]
@mikkeldk rerun the requirement install command

**Comment by Technoblazed** [comment]
@splewis if I create some installation guides are you up for putting them on the wiki?

**Comment by MikkelDK** [comment]
How are it's possible for starting?

**Comment by Technoblazed** [comment]
@MikkelDK are you using apache or nginx?

**Comment by MikkelDK** [comment]
@Technoblazed Apache ;)

**Comment by Technoblazed** [comment]
@MikkelDK Have you carried out the instructions:
https://github.com/splewis/get5-web#deployed-using-apache2-with-mod_wsgi

**Comment by MikkelDK** [comment]
@Technoblazed 

- Invalid command 'WSGIScriptAlias' < hmm what todo?

> 
<VirtualHost *:80>
        WSGIScriptAlias / /var/www/html/get5-web/get5.wsgi

        <Directory /var/www/html/get5-web>
            Order deny,allow
            Allow from all
        </Directory>

        Alias /static /var/www/html/get5-web/get5/static
        <Directory /var/www/html/get5-web/get5/static>
            Order allow,deny
            Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
>

**Comment by Technoblazed** [comment]
```
See the official flask documentation for installation requirements.
```
Install it: http://flask.pocoo.org/docs/0.11/deploying/mod_wsgi/

**Comment by MikkelDK** [comment]
@Technoblazed 

Opps.. i didnt see i needed install haha! :)

Now it installed, what can i do now?

**Comment by Technoblazed** [comment]
Restart apache and it should work I guess?  Kind of a grey area, I use nginx.

**Comment by Technoblazed** [comment]
@MikkelDK You also have no `ServerName` directive in your apache config:

```
Note: due to a limitation in how API requests are sent from the game server to the web server, you must have a domain associated with the web panel. Just hosting it at an ip:port will not work and will cause match updates from the game server to not reach the web panel.
```

**Comment by MikkelDK** [comment]
Oh. ;) i will fix A record ^^

**Comment by MikkelDK** [comment]
So, the site will not work for "visible" ?

Example this screenshot:
![rofl](https://cloud.githubusercontent.com/assets/5301047/21108193/a1ce9922-c094-11e6-8523-7e100cb9ccf2.png)

**Comment by Technoblazed** [comment]
@MikkelDK did you update your get5.wsgi with the path?

**Comment by MikkelDK** [comment]
@Technoblazed - I have now updated the file jeps! ;) forget to add /html/ (because it's debian8) ;d

**Comment by Technoblazed** [comment]
Does it work?

**Comment by MikkelDK** [comment]
it's same, dunno about i needed to run something file in background?

**Comment by Technoblazed** [comment]
Wait for @splewis to get on, I don't use apache :(

**Comment by MikkelDK** [comment]
I will wait! ;) - yeah i dont know so much about nginx (i'm not expert with it.) :)

**Comment by MikkelDK** [comment]
I got it fixed!

Did forget to set www-data on get5-web ^^

**Comment by MikkelDK** [comment]
After "sign in as steam"

Error found:
Sorry, unexpected error: object of type 'NoneType' has no len()
What can i do?

**Comment by Technoblazed** [comment]
I feel like you installed this incorrectly, in all honesty

**Comment by MikkelDK** [comment]
So it's not possible install under /var/www/html/ example? Hm but the site could work. Just only steam as sign dont do.

**Comment by Technoblazed** [comment]
Mine is installed under `/home/drive-1/webservers/compete-admin.xxx.com` lol, did you try googling the error?

**Comment by MikkelDK** [comment]
Fixed the issues (did reinstall database!) and now it works - thanks you!

**Comment by Technoblazed** [comment]
Literally gonna make install guides for each OS, lmao

**Comment by MikkelDK** [comment]
Do it :D

**Comment by MikkelDK** [comment]
Are it's possible for upload team logos?

**Comment by Technoblazed** [comment]
https://github.com/splewis/get5-web/issues/16

```
Right now you just drag files into get5/static/img/logos
```

**Comment by MikkelDK** [comment]
@Technoblazed - Thanks! ;)

**Comment by MikkelDK** [comment]
Does the "logos" needed to be uploaded/downloaded for clientside?

**Comment by Technoblazed** [comment]
A) Stop opening and closing :( Spam of emails is insane.
B) You need this - https://forums.alliedmods.net/showthread.php?t=258206 and need to configure a fastdl for logos to download. Do not forget the .cfg for each logo on the server.

**Comment by splewis** [comment]
The logos aren't well documented, but you don't need any extra plugins besides the two get5 ones (get5.smx and get5_apistats.smx). 

The apistats plugin downloads the logos from the website and get5 adds them to the download table.

**Comment by splewis** [comment]
As far as I can tell this is resolved. Reopen if that's not the case.

**Comment by MikkelDK** [comment]
I'm sorry for bring this up again! . - is there some guide for getting the web to works via nginx? - as example uwsgi. or something. ;) since i'm using nginx now, and not longer apache2.

**Comment by Technoblazed** [comment]
There isn't a guide for setting it up with nginx.
