### ISSUE TITLE
Missing section from original Get5 Plugin in Panel

### ISSUE THREAD

**Issue by TandelK** [splewis/get5-web#37]
After version 5.0 of Get5 , Clan Tags has been added to the servers . This update is not yet available on the Get5-web yet. 

Also for Logo it is better to add Upload button instead of uploading all the logos . We can make it a fastdl to the same folder which might be responding with the server ,

**Comment by Technoblazed** [comment]
Tags are available on get5-web?

**Comment by Technoblazed** [comment]
I know because I did the push myself

**Comment by TandelK** [comment]
Wait might be left to upgrade the panel to new version, i manually downloaded the panel and tried it, does i need to keep something in mind while updating the panel ?

**Comment by Technoblazed** [comment]
Update the panel, and make sure you run the database migrate command again

**Comment by splewis** [comment]
It's been there since https://github.com/splewis/get5-web/pull/33. You do need to run the upgrade command though: ``./manager.py db upgrade``
