### ISSUE TITLE
How to setup public servers

### ISSUE THREAD

**Issue by dzagu** [splewis/get5-web#39]
Hello, its possibble to setup public server? I mean when someone add server everyone can play match on him if its unused.

**Comment by Technoblazed** [comment]
This is the web repo for Get5. Get5 is a plugin for preconfigured tournaments and scrims. Use https://github.com/splewis/csgo-pug-setup if you're just looking for what you're asking for.

**Comment by dzagu** [comment]
1. This is my website: http://aruba.globalelite.pl/matches
2. I added server there, everything works now.
3. What I want now is that **everyone** who sign in can create match on my server if he is empty.

**Comment by Technoblazed** [comment]
Don't include the `WHITELISTED_IDS` array in your settings, done

**Comment by splewis** [comment]
I understand your request. I'd think of it something like a "public server" option, the same way an admin user can create a "public team" anyone can access. Sounds worthwhile to me.

**Comment by dzagu** [comment]
> Don't include the WHITELISTED_IDS array in your config. done.
Its empty and players still cant choose my server, only me.
I want create something like public 5v5 platform, if server is free someone can play mix 5v5 on it.

**Comment by splewis** [comment]
Maybe I wasn't clear. This isn't currently possible.

**Comment by dzagu** [comment]
Its easy to make, like 20 lines of code?

**Comment by splewis** [comment]
Closing since #52 is a clearer request.
