### ISSUE TITLE
Pause from the Panel is not working

### ISSUE THREAD

**Issue by TandelK** [splewis/get5-web#40]
If we try to use Pause Match from the Panel, it doesnt seems to do anything . It doesnt even send any commands to the server.

**Comment by keeradfun** [comment]
Changing sm_pause to mp_pause_match in match.py line 304.
changing sm_unpause to mp_unpause_match in match.py 319.
helped me to fix the issue.

**Comment by Technoblazed** [comment]
sm_pause is a command added by get5, which means that either there's an issue with your installation or something else, do you have any error logs on your servers?

**Comment by TandelK** [comment]
There are no error logs on the server but if i do sm_pause command it works fine manually via RCON

**Comment by splewis** [comment]
I've never been able to reproduce this, so I'm going to close it. If you think there's still a problem, feel free to reopen.
