### ISSUE TITLE
[Question] Implement the API in nodeJS?

### ISSUE THREAD

**Issue by cre0n** [splewis/get5-web#41]
Hello,
I just wanted to ask quickly if it's possible to use the API in a nodeJS Express server as well somehow, as I don't have any experience with Flask/Python?

Thanks in advance!

**Comment by splewis** [comment]
I'm not sure I understand what you mean. This project, get5-web, defines an API that is meant to be called from game servers.  

You could replace the get5-web project here with a similar API implementation that was written in any language you want.

**Comment by cre0n** [comment]
I'm sorry, should've explained it better:
I recently started making websites as a "easier step" before trying myself at actual programs/scripts in SourcePawn etc, and I've really been a fan of your projects so I thought I might just ask if it's possible, I didn't know APIs are actually "universal", thought it always depends on something. Thanks for your answer, could you give me a hint where I can point on to implement the API on my nodeJS website? :) Like, which are the files I have to look into and which can I ignore?

**Comment by cre0n** [comment]
So I figured out the API Key is set over rcon, being a random string (right?), but what do I put in the url api convar, and how do I actually access the "data package sent"? Is it a JSON text file? Do you have any link for me to understand that API mechanism? :S Is it your own, or are you using something else for it, so theres a documentation about it somewhere?

Again thanks a lot!

**Comment by Technoblazed** [comment]
Honestly, if you read through the python code, its SUPER clear to see what stuff is and how it's done.

**Comment by cre0n** [comment]
I just started with trying myself on nodeJS, dont have any other coding experience and everything looks object oriented so I don't know what's defined and whats a preset python function :(

**Comment by Technoblazed** [comment]
If you're just learning nodejs, this definitely isn't a project to start with unless you really enjoy a challenge, start with something a tad easier and learn the basics.

**Comment by cre0n** [comment]
I just don't understand, where do all the information of the < % % > clauses in the html sites come from? Is there like a app.js in nodeJS, that is being executed in Flask?
I just need a tip where I find the "logic" behind it, it's okay if its in python, but I'm not able to see the communication point.

The information given in the readme;
"When stats begin to update (map start, round end, map end, series end), the game server plugins will send HTTP requests to the web server, using a per-match API token set in the get5_web_api_key cvar when the match was assigned to the server"
is just too general for me, I would really appreciate someone just telling me how the sourcepawn plugin hooks into the website, e.g. what I have to put as "get5_web_api_url" (a domain? an IP? a specific link to a folder in the www/html/ folder?), and in which .py file the code for e.g. the "match finished" event lies

**Comment by splewis** [comment]
html templates: http://flask.pocoo.org/docs/0.12/quickstart/#rendering-templates

api implementation: https://github.com/splewis/get5-web/blob/master/get5/api.py

The game server sends [HTTP requests](https://github.com/splewis/get5/blob/master/scripting/get5_apistats.sp#L116) to a domain that go to the routing functions in that file. Each function saves things into the database, and the most of the other get5-web files are concerned with rendering those stats on html pages.

**Comment by splewis** [comment]
Closing since there's no feature/bug here.
