### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by JackBultitude** [splewis/get5-web#43]
Trying to install get5-web onto Ubuntu 16.04 but when browsing to the site a connection refused is returned.

**Comment by Technoblazed** [comment]
Did you setup your wsgi correctly?

**Comment by smilezHD** [comment]
yes to my knowlage i did

**Comment by Technoblazed** [comment]
Error 500 is vague, do you have any further information?

**Comment by smilezHD** [comment]
mainly just get connection refuesed when connecting to the domain cp.emzgaming.uk

**Comment by Technoblazed** [comment]
- Is the DNS configured correctly.

- Is the webserver running?

**Comment by smilezHD** [comment]
yep both the DNS and the webserver are working correctly

**Comment by Technoblazed** [comment]
Your DNS JUST updated, are you sure you didn't just change it :^)

**Comment by smilezHD** [comment]
nope not touched it

**Comment by smilezHD** [comment]
Apache

**Comment by Technoblazed** [comment]
```

Starting Nmap 7.01 ( https://nmap.org ) at 2017-04-03 18:04 BST
Nmap scan report for cp.emzgaming.uk (139.59.190.87)
Host is up (0.077s latency).
PORT   STATE  SERVICE
80/tcp closed http

Nmap done: 1 IP address (1 host up) scanned in 0.37 seconds
```

Check your webserver again for me :^)

**Comment by smilezHD** [comment]
m running the command to start Apache (The webserver) and it isnt returning any errors (acting exactly as it should if it were succesful) but when i run the command to see the state of all processes on the server, it reports that apache is not active

**Comment by smilezHD** [comment]
situations changed, i was able to find out why the connection was being refused. Apache was starting and throwing a fit about the fact we had a python module for apache installed so I removed it and now apache acc starts, however it is now dishing out error 500's front right and centre

**Comment by Technoblazed** [comment]
Could you send me a copy of your wsgi?

**Comment by smilezHD** [comment]
were can i find the wsgi?

**Comment by Technoblazed** [comment]
When you installed get5-web, you should have also created a get5.wsgi

**Comment by smilezHD** [comment]
#!/usr/bin/python

activate_this = '/var/www/get5-web/venv/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import sys
import logging
logging.basicConfig(stream=sys.stderr)

folder = "/var/www/get5-web"
if not folder in sys.path:
    sys.path.insert(0, folder)
sys.path.insert(0,"")

from get5 import app as application
import get5
get5.register_blueprints()

also note that /var/www/get5-web/venv/bin/activate_this.py does not exist on our server

**Comment by Technoblazed** [comment]
Did you not create your VENV yet, as instructed, in the instructions?

**Comment by smilezHD** [comment]
yep we did

**Comment by Technoblazed** [comment]
If you did, there would be a venv/bin/activate_this.py :thinking:

**Comment by smilezHD** [comment]
we ran the command to create venv but there is definitly no /var/www/get5-web/venv directory the only thing inside is /var/www/get5-web is get5.wsgi

**Comment by Technoblazed** [comment]
Were there any errors when you ran the command to create the venv, or anything that looked out of place?

**Comment by m4xwellmorris** [comment]
Hey @Technoblazed im taking over from @smilezHD as we work on the same team. The file ~/get5-web/venv/bin/activate_this.py does exist however it is /var/www/get5-web/venv/bin/activate_this.py that does not exist. Can you advise on why the WSGI file contains this dir when the install instructions do not specify a need to create a virtualenv inside the /var/www/get5-web dir.

**Comment by Technoblazed** [comment]
Ohhhhhhh, it assumes you're going to stick it in the apache webroot, just update your WSGI to the path of the directory your venv is ACTUALLY in :^)

**Comment by m4xwellmorris** [comment]
Ahh I see. Would it be a more elegent solution to simply move everything from ~/get5-web into /var/www/get5-web and leave config as is?

**Comment by Technoblazed** [comment]
Can do!

**Comment by m4xwellmorris** [comment]
Cheers so much mate! Fully working now!

**Comment by splewis** [comment]
... I guess this is resolved.

As always, pull requests for documentation improvements are also welcomed.

**Comment by Technoblazed** [comment]
@splewis Any preference to how you want docs pushing?
