### ISSUE TITLE
Either get5 or get5_apistats plugin missing

### ISSUE THREAD

**Issue by smilezHD** [splewis/get5-web#46]
when i try to create a match it comes up with Either "get5 or get5_apistats plugin missing" then i check my /addons/sourcemod/plugins they are both in there

**Comment by Technoblazed** [comment]
Could I get the output of 
'sm plugins list'

**Comment by smilezHD** [comment]
[SM] Listing 19 plugins:
  01 "Admin File Reader" (1.8.0.5973) by AlliedModders LLC
  02 "Admin Help" (1.8.0.5973) by AlliedModders LLC
  03 "Admin Menu" (1.8.0.5973) by AlliedModders LLC
  04 "Anti-Flood" (1.8.0.5973) by AlliedModders LLC
  05 "Basic Ban Commands" (1.8.0.5973) by AlliedModders LLC
  06 "Basic Chat" (1.8.0.5973) by AlliedModders LLC
  07 "Basic Comm Control" (1.8.0.5973) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.5973) by AlliedModders LLC
  09 "Basic Info Triggers" (1.8.0.5973) by AlliedModders LLC
  10 "Basic Votes" (1.8.0.5973) by AlliedModders LLC
  11 "Client Preferences" (1.8.0.5973) by AlliedModders LLC
  12 "Fun Commands" (1.8.0.5973) by AlliedModders LLC
  13 "Fun Votes" (1.8.0.5973) by AlliedModders LLC
  14 "Get5" (0.5.1) by splewis
  15 <Failed> "Get5 Web API Integration" (0.5.1) by splewis
  16 "Nextmap" (1.8.0.5973) by AlliedModders LLC
  17 "Player Commands" (1.8.0.5973) by AlliedModders LLC
  18 "Reserved Slots" (1.8.0.5973) by AlliedModders LLC
  19 "Sound Commands" (1.8.0.5973) by AlliedModders LLC
Errors:
get5_apistats.smx (Get5 Web API Integration): Required extension "SteamWorks" file("SteamWorks.ext") not running

**Comment by Technoblazed** [comment]
You're missing the SteamWorks extension, get it here: http://users.alliedmods.net/~kyles/builds/SteamWorks/

**Comment by smilezHD** [comment]
installed the top one into the server and still getting the error
still says not installed

**Comment by smilezHD** [comment]
just noticed its linux not windows "i think"

**Comment by smilezHD** [comment]
yet still get it

**Comment by smilezHD** [comment]
lies it created a seperate directory now get error 
Errors:
get5_apistats.smx (Get5 Web API Integration): Required extension "SMJansson" file("smjansson.ext") not running

**Comment by smilezHD** [comment]
[SM] Listing 24 plugins:
  01 "Admin File Reader" (1.8.0.5973) by AlliedModders LLC
  02 "Admin Help" (1.8.0.5973) by AlliedModders LLC
  03 "Admin Menu" (1.8.0.5973) by AlliedModders LLC
  04 "Anti-Flood" (1.8.0.5973) by AlliedModders LLC
  05 "Basic Ban Commands" (1.8.0.5973) by AlliedModders LLC
  06 "Basic Chat" (1.8.0.5973) by AlliedModders LLC
  07 "Basic Comm Control" (1.8.0.5973) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.5973) by AlliedModders LLC
  09 "Basic Info Triggers" (1.8.0.5973) by AlliedModders LLC
  10 "Basic Votes" (1.8.0.5973) by AlliedModders LLC
  11 "Client Preferences" (1.8.0.5973) by AlliedModders LLC
  12 "Fun Commands" (1.8.0.5973) by AlliedModders LLC
  13 "Fun Votes" (1.8.0.5973) by AlliedModders LLC
  14 "Get5" (0.5.1) by splewis
  15 <Failed> "Get5 Web API Integration" (0.5.1) by splewis
  16 "Nextmap" (1.8.0.5973) by AlliedModders LLC
  17 "Player Commands" (1.8.0.5973) by AlliedModders LLC
  18 "Reserved Slots" (1.8.0.5973) by AlliedModders LLC
  19 <Failed> "smjansson.example-01.smx"
  20 <Failed> "smjansson.example-02.smx"
  21 <Failed> "smjansson.example-03.smx"
  22 <Failed> "smjansson.example-04.smx"
  23 <Failed> "SMJansson, Test, Create JSON" (0.0.1) by Thrawn
  24 "Sound Commands" (1.8.0.5973) by AlliedModders LLC
Errors:
get5_apistats.smx (Get5 Web API Integration): Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-01.smx: Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-02.smx: Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-03.smx: Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-04.smx: Required extension "SMJansson" file("smjansson.ext") not running
smjansson.test.smx (SMJansson, Test, Create JSON): Required extension "SMJansson" file("smjansson.ext") not running

**Comment by Technoblazed** [comment]
Delete all of the sdk files and plugins you moved in, you just need the binary

**Comment by splewis** [comment]
I think the question here is: "how do I install smjansson?"

The answer: go to [its forum thread](https://forums.alliedmods.net/showthread.php?t=184604), download the binaries (smjansson_2.3.1.3_binaries.zip), extract those files in ``addons/sourcemod/extensions``. (you really only need the .so  for linux or the .dll for windows, but there's no harm in having both)

In the future you can diagnose problems much easier if you look at sourcemod's error logs first as well in ``addons/sourcemod/logs``.

**Comment by splewis** [comment]
This is unrelated to get5-web itself, so closing.

**Comment by Muhamdmuaz** [comment]
rcon sm plugins list
[SM] Listing 25 plugins:
  01 "Client Preferences" (1.9.0.6261) by AlliedModders LLC
  02 <Failed> "SMJansson, Test, Create JSON" (0.0.1) by Thrawn
  03 "Fun Commands" (1.9.0.6261) by AlliedModders LLC
  04 "Basic Ban Commands" (1.9.0.6261) by AlliedModders LLC
  05 "Reserved Slots" (1.9.0.6261) by AlliedModders LLC
  06 "Basic Info Triggers" (1.9.0.6261) by AlliedModders LLC
  07 "Player Commands" (1.9.0.6261) by AlliedModders LLC
  08 "Admin Menu" (1.9.0.6261) by AlliedModders LLC
  09 <Failed> "smjansson.example-04.smx"
  10 "Nextmap" (1.9.0.6261) by AlliedModders LLC
  11 <Failed> "Get5 Web API Integration" (0.6.0) by splewis
  12 "Admin File Reader" (1.9.0.6261) by AlliedModders LLC
  13 "Basic Comm Control" (1.9.0.6261) by AlliedModders LLC
  14 <Error> "Get5 MySQL stats" (0.6.0) by splewis
  15 "Get5" (0.6.0) by splewis
  16 "Basic Commands" (1.9.0.6261) by AlliedModders LLC
  17 "Basic Chat" (1.9.0.6261) by AlliedModders LLC
  18 <Failed> "smjansson.example-02.smx"
  19 "Anti-Flood" (1.9.0.6261) by AlliedModders LLC
  20 "Basic Votes" (1.9.0.6261) by AlliedModders LLC
  21 <Failed> "smjansson.example-03.smx"
  22 "Sound Commands" (1.9.0.6261) by AlliedModders LLC
  23 "Admin Help" (1.9.0.6261) by AlliedModders LLC
  24 <Failed> "smjansson.example-01.smx"
  25 "Fun Votes" (1.9.0.6261) by AlliedModders LLC
Errors:
smjansson.test.smx (SMJansson, Test, Create JSON): Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-04.smx: Required extension "SMJansson" file("smjansson.ext") not running
get5_apistats.smx (Get5 Web API Integration): Required extension "SMJansson" file("smjansson.ext") not running
get5_mysqlstats.smx (Get5 MySQL stats): Error detected in plugin startup (see error logs)
smjansson.example-02.smx: Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-03.smx: Required extension "SMJansson" file("smjansson.ext") not running
smjansson.example-01.smx: Required extension "SMJansson" file("smjansson.ext") not running
L 12/03/2018 - 15:55:19:

**Comment by TandelK** [comment]
It clearly says smjasson extension is missing , i think you misunderstood SMJansson Extension and you have added a plugin which is only for testing SMJansson Extension running or not. 

You already have get5_apistats loaded and i would not recommend loading both apistats as well as mysqlstats as apistats does some SQL recording on the panel instead of local database.
