### ISSUE TITLE
admin, casters, coach

### ISSUE THREAD

**Issue by smilezHD** [splewis/get5-web#47]
hello, is there a cfg file i need to edit so that admins can get on casters can get on and coaches,
coaches i could add to the teams roster but admins and casters cannot connect?

**Comment by Technoblazed** [comment]
Not for the webclient, inside your game files, you can use:

```
get5_addplayer steamid spec
```

to add them to the spectator team.

Might not be 100% accurate on that usage, but youll figure it out.

**Comment by smilezHD** [comment]
i get the error Unknown team: must be one of team1, team2, spec

**Comment by Technoblazed** [comment]
Do 
```get5_addplayer```
with nothing after it, my order is probably wrong.

**Comment by smilezHD** [comment]
still get the error Unknown team: must be one of team1, team2, spec

**Comment by smilezHD** [comment]
get5_addplayer <auth> <team1|team2|spec>

**Comment by smilezHD** [comment]
still get the same error

**Comment by Technoblazed** [comment]
Add me on steam, https://steamcommunity.com/id/technoblazed

**Comment by smilezHD** [comment]
sent

**Comment by splewis** [comment]
The syntax is ``get5_addplayer <auth> <team1|team2|spec>``. If there's a bug with that command you should report it for the plugin itself at https://github.com/splewis/get5/issues

There's an outstanding bug for adding players to spectate already: https://github.com/splewis/get5-web/issues/8
