### ISSUE TITLE
Creating 1v1 tournament 

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5-web#53]
We want have a tournament of 1v1 with 3 custom maps and its best of 3.
How can i make use of get5 webpanel in this tournament and how can i add custom configs into this.

**Comment by Technoblazed** [comment]
@keeradfun Someone actually contacted me about that exact same thing today, super easy. Custom configs would be stored on the server, and the maps are added through the get5-web config. (Any chance you know the person that contacted me, "fizzl3"?)

**Comment by keeradfun** [comment]
Thanks i will test it and let you know and i dont know about fizzl3 and im contacting you for the first time.
You fold got any discord server so that i can get some help when i required. :)

**Comment by splewis** [comment]
Sorry, the webpanel doesn't have any support for skipping side selection yet.

**Comment by keeradfun** [comment]
Like can i add one more button in series type. Where it pass-on jason value like this
"skip_veto": true,
"map_sides":
[
	"team1_ct",
	"team1_t",
	"team1_t"
],
"maplist":
[
	"de_cache",
	"de_mirage",
	"de_overpass",
]

**Comment by splewis** [comment]
I created https://github.com/splewis/get5-web/issues/58, which I think describes the request here, so I'm closing this.
