### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by coolen555** [splewis/get5-web#54]
I couldn't find anywhere else to put it or a way to contact you.

Would it be possible to get windows support? I'm currently running my CS:GO server on a dedicated server running Windows Server 2012 R2 and was wondering if it was possible to ever get Windows Support? I'd love to be able to use the webpanel.

**Comment by Technoblazed** [comment]
Install Apache for windows. Follow pretty much the same instructions provided on the Readme.

**Comment by coolen555** [comment]
The instructions don't make too much sense to me, too complicated for me atleast. I'll just wait until somone makes instructions for windows or something

**Comment by splewis** [comment]
Sorry, I don't plan on supporting windows anytime soon. Anyone who wants to use this on windows is on their own.
