### ISSUE TITLE
Installing with Caddy

### ISSUE THREAD

**Issue by iSach** [splewis/get5-web#57]
Hello,

I'm a bit nooby with all that but I'm using Caddy and I'd like to install get5-web with it, but I can't figure out how to.

I'd like to install it to have my own logo in game.

Thanks in advance,
Sacha

**Comment by splewis** [comment]
I don't know anything about Caddy and can't help there.

The get5 plugin has support for logos if they're uploaded to the game server (to ``resource/flash/econ/tournaments/teams``), the web interface isn't need to make that work.

**Comment by iSach** [comment]
Oh okay thanks a lot! :)

Thanks also for all the amazing plugins you make :D
