### ISSUE TITLE
API request failed, HTTP status code = 0

### ISSUE THREAD

**Issue by csgentr** [splewis/get5-web#6]
hello, ı have a problem about this error "API request failed, HTTP status code = 0"

everthing is working find very well, I'm creating match server starting knife round vsvs everything.

but ıt doesn't show on web page, its still writing on web page match status "Pending"

and then I checked my server logs, it was writing 

L 07/13/2016 - 23:04:50: SourceMod error session started
L 07/13/2016 - 23:04:50: Info (map "de_dust2") (file "errors_20160713.log")
L 07/13/2016 - 23:04:50: [SM] Plugin encountered error 15: Array index is out of bounds
L 07/13/2016 - 23:04:50: [SM] Displaying call stack trace for plugin "get5_apistats.smx":
L 07/13/2016 - 23:04:50: [SM]   [0]  Line 68, get5_apistats.sp::ApiInfoChanged()
L 07/13/2016 - 23:05:06: Error log file session closed.
L 07/13/2016 - 23:09:02: SourceMod error session started
L 07/13/2016 - 23:09:02: Info (map "de_dust2") (file "errors_20160713.log")
L 07/13/2016 - 23:09:02: [get5_apistats.smx] API request failed, HTTP status code = 0
L 07/13/2016 - 23:09:02: [get5_apistats.smx] ÈVaë =ßìT
L 07/13/2016 - 23:09:46: [get5_apistats.smx] API request failed, HTTP status code = 0
L 07/13/2016 - 23:09:46: [get5_apistats.smx]  àî àî˜laë˜laë
L 07/13/2016 - 23:09:46: [get5_apistats.smx] API request failed, HTTP status code = 0

**Comment by splewis** [comment]
The 1st error (which is itself a bug) indicated that the ``get5_web_api_url`` cvar is the empty string, which is why the requests fail. 

It's supposed to be set in the get5 match config loaded (in the ``cvars`` section) - you could try checking to see if it is set there.

**Comment by splewis** [comment]
I would also like to suggest that you do not assert copyright over things that you do not hold a copyright to. I'm will not provide support to anyone doing that.

**Comment by csgentr** [comment]
ok sorry about that :(
