### ISSUE TITLE
Connection to upstream refused

### ISSUE THREAD

**Issue by boXseven** [splewis/get5-web#63]
hi, wasnt that easy to set it up but i think im close to?
i was able to write the data to the mysql db but now im getting this error from the get5.wsgi in my www folder.
- Connection to upstream refused

i cloned the git to /get5-web and did all the steps. i wondered about the step clone it to www? beside that im not able to, i have it in /get5-web already.
i configured the get5.wsgi that it point to /get5-web (activate_this = '/var/get5-web/venv/bin/activate_this.py' and folder = "/var/get5-web").

my website is running as Python WSGI with Python 2.7.12

hopefully you can help me a lil bit.

**Comment by boXseven** [comment]
ok, now i got an interface but the steam sign in doesnt work.
http://unkn9wn.pythonanywhere.com/

**Comment by Technoblazed** [comment]
Probably host related.

**Comment by boXseven** [comment]
it doesnt have smth to do with the api key or?

**Comment by Technoblazed** [comment]
The api key is only used to get user data, I just assumed that you'd actually put an api key in...

**Comment by boXseven** [comment]
yeah sure i did, but i dunno why he isnt redirecting
i registered the domain name http://unkn9wn.pythonanywhere.com/ and i think thats correct

**Comment by boXseven** [comment]
cant get it to work, everything works so far with the installation beside this
```
Collecting alembic==0.8.6 (from -r requirements.txt (line 1))
/home/unkn9wN/get5-web/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) ex
tension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve t
his. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/unkn9wN/get5-web/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 f
rom configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/s
ecurity.html#insecureplatformwarning.
  InsecurePlatformWarning
```

does this explain the behavior?

**Comment by splewis** [comment]
Maybe. I don't have much to investigate and help, though.

As the error says, maybe you could use a different version of python. From my web server:
```
$ ~ python --version
Python 2.7.6
```
What version of python are you using?

**Comment by boXseven** [comment]
11:32 ~ $ python --version
Python 2.7.6
