### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by boXseven** [splewis/get5-web#64]
Sadly i have the next problem.
Somehow im not able to create a server.

`18:37:23 get5_web_avaliable
18:37:23 {
             "plugin_version": "0.5.2",
             "gamestate": 0,
             "avaliable": 1
         }`

`18:38:01 sm plugins list
18:38:01 [SM] Listing 20 plugins:
           01 "Basic Info Triggers" (1.8.0.5998) by AlliedModders LLC
           02 "Basic Ban Commands" (1.8.0.5998) by AlliedModders LLC
           03 "Client Preferences" (1.8.0.5998) by AlliedModders LLC
           04 "Basic Commands" (1.8.0.5998) by AlliedModders LLC
           05 <Failed> "Nextmap" (1.8.0.5998) by AlliedModders LLC
           06 "Fun Votes" (1.8.0.5998) by AlliedModders LLC
           07 "Get5" (0.5.2) by splewis
           08 "[CS:GO] Damage printer" (1.0.0) by splewis
           09 "Basic Chat" (1.8.0.5998) by AlliedModders LLC
           10 "Admin Help" (1.8.0.5998) by AlliedModders LLC
           11 "Basic Comm Control" (1.8.0.5998) by AlliedModders LLC
           12 "Admin File Reader" (1.8.0.5998) by AlliedModders LLC
           13 "Fun Commands" (1.8.0.5998) by AlliedModders LLC
           14 "Sound Commands" (1.8.0.5998) by AlliedModders LLC
           15 "Reserved Slots" (1.8.0.5998) by AlliedModders LLC
           16 "Player Commands" (1.8.0.5998) by AlliedModders LLC
           17 "Admin Menu" (1.8.0.5998) by AlliedModders LLC
           18 "Basic Votes" (1.8.0.5998) by AlliedModders LLC
           19 "Anti-Flood" (1.8.0.5998) by AlliedModders LLC
           20 "Get5 Web API Integration" (0.5.2) by splewis`

**Comment by Technoblazed** [comment]
That's useless information. Provide information about the steps you're taking.

**Comment by boXseven** [comment]
Well, that was just to let you know that everything should be installed correctly.
I think the steps are obvious.

Go to the panel, log in, click add a server and fill in the information or what do you mean.

**Comment by Technoblazed** [comment]
See, that's more information!

The `Failed to connect to server` notification appears when you're adding a server, and the server is not online. Can you confirm that the server you're attempting to add is actually turned on?

**Comment by boXseven** [comment]
yeah, its a game server from ngz on port 27015

**Comment by Technoblazed** [comment]
An issue similar to this has been brought up before, could you check if there are any firewalls or restrictions that could be blocking the connection to the server?

**Comment by splewis** [comment]
I don't think there's much I can help with. I would try connecting via rcon to the game server manually. Maybe there's a command line tool that can help test that.

**Comment by boXseven** [comment]
there must be something with my installation, because i was able to add the server at your site.
server id: #141

another question for me is, do i need the get5_mysqlstats.smx? what does it do?
i couldnt find anything about this in the documentation.

**Comment by boXseven** [comment]
any idea what i can check next?

**Comment by Mrciller** [comment]
i got that problem too. I still dont know how to fix it i tried at the start settings         +rcon_password "password" -usercon

**Comment by Technoblazed** [comment]
@Mrciller Make another issue, or clearly explain exactly what your issue is. This issue already has a lack of details as it is, and it's almost half a year old.

**Comment by splewis** [comment]
I don't think there's anything to fix here.
