### ISSUE TITLE
New Installation on Debian 8

### ISSUE THREAD

**Issue by FaNNboii** [splewis/get5-web#68]
Hey, i wanted to install get5-web on my new Server. I installed python, mysql and apache2 and then step by step by guide. But i always get this error after pip install -r requirements.txt

EnvironmentError: mysql_config not found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-3UAk                                                   FB/MySQL-python
Storing debug log for failure in /root/.pip/pip.log
(venv)root@becher:/var/www/html/get5-web#

**Comment by Technoblazed** [comment]
`apt-get install libmysqlclient-dev`

Search past issues before creating a new issue, there's a bunch with this already.

**Comment by FaNNboii** [comment]
Ok now when i connect to the website it says: 500 Internal Server Error

and in error.log

[Tue Oct 03 11:44:49.374331 2017] [mpm_prefork:notice] [pid 23463] AH00163: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Tue Oct 03 11:44:49.374374 2017] [core:notice] [pid 23463] AH00094: Command line: '/usr/sbin/apache2'
[Tue Oct 03 11:44:56.924073 2017] [mpm_prefork:notice] [pid 23463] AH00169: caught SIGTERM, shutting down
[Tue Oct 03 11:44:57.791030 2017] [wsgi:warn] [pid 23527] mod_wsgi: Compiled for Python/2.7.8.
[Tue Oct 03 11:44:57.791066 2017] [wsgi:warn] [pid 23527] mod_wsgi: Runtime using Python/2.7.9.
[Tue Oct 03 11:44:57.793163 2017] [mpm_prefork:notice] [pid 23527] AH00163: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Tue Oct 03 11:44:57.793187 2017] [core:notice] [pid 23527] AH00094: Command line: '/usr/sbin/apache2'
[Tue Oct 03 11:46:55.685970 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432] mod_wsgi (pid=23540): Target WSGI script '/var/www/html/get5-web/get5.wsgi' cannot be loaded as Python module.
[Tue Oct 03 11:46:55.686014 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432] mod_wsgi (pid=23540): Exception occurred processing WSGI script '/var/www/html/get5-web/get5.wsgi'.
[Tue Oct 03 11:46:55.686049 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432] Traceback (most recent call last):
[Tue Oct 03 11:46:55.686071 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]   File "/var/www/html/get5-web/get5.wsgi", line 15, in <module>
[Tue Oct 03 11:46:55.686135 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]     from get5 import app as application
[Tue Oct 03 11:46:55.686159 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]   File "/var/www/html/get5-web/get5/__init__.py", line 73, in <module>
[Tue Oct 03 11:46:55.686319 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]     app.config['LOG_PATH'], when='midnight')
[Tue Oct 03 11:46:55.686334 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]   File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
[Tue Oct 03 11:46:55.687654 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Tue Oct 03 11:46:55.687673 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
[Tue Oct 03 11:46:55.687694 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Tue Oct 03 11:46:55.687717 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]   File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
[Tue Oct 03 11:46:55.688986 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]     StreamHandler.__init__(self, self._open())
[Tue Oct 03 11:46:55.689004 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]   File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
[Tue Oct 03 11:46:55.689024 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432]     stream = open(self.baseFilename, self.mode)
[Tue Oct 03 11:46:55.689047 2017] [wsgi:error] [pid 23540] [client 79.225.106.113:62432] IOError: [Errno 13] Permission denied: '/var/www/html/get5-web/logs/get5.log'
[Tue Oct 03 11:46:56.930915 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434] mod_wsgi (pid=23541): Target WSGI script '/var/www/html/get5-web/get5.wsgi' cannot be loaded as Python module.
[Tue Oct 03 11:46:56.930983 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434] mod_wsgi (pid=23541): Exception occurred processing WSGI script '/var/www/html/get5-web/get5.wsgi'.
[Tue Oct 03 11:46:56.931035 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434] Traceback (most recent call last):
[Tue Oct 03 11:46:56.931061 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]   File "/var/www/html/get5-web/get5.wsgi", line 15, in <module>
[Tue Oct 03 11:46:56.931227 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]     from get5 import app as application
[Tue Oct 03 11:46:56.931249 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]   File "/var/www/html/get5-web/get5/__init__.py", line 73, in <module>
[Tue Oct 03 11:46:56.931425 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]     app.config['LOG_PATH'], when='midnight')
[Tue Oct 03 11:46:56.931442 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]   File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
[Tue Oct 03 11:46:56.932068 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Tue Oct 03 11:46:56.932086 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
[Tue Oct 03 11:46:56.932111 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Tue Oct 03 11:46:56.932125 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]   File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
[Tue Oct 03 11:46:56.933051 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]     StreamHandler.__init__(self, self._open())
[Tue Oct 03 11:46:56.933079 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]   File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
[Tue Oct 03 11:46:56.933110 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434]     stream = open(self.baseFilename, self.mode)
[Tue Oct 03 11:46:56.933142 2017] [wsgi:error] [pid 23541] [client 79.225.106.113:62434] IOError: [Errno 13] Permission denied: '/var/www/html/get5-web/logs/get5.log'
[Tue Oct 03 11:46:58.047125 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435] mod_wsgi (pid=23543): Target WSGI script '/var/www/html/get5-web/get5.wsgi' cannot be loaded as Python module.
[Tue Oct 03 11:46:58.047172 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435] mod_wsgi (pid=23543): Exception occurred processing WSGI script '/var/www/html/get5-web/get5.wsgi'.
[Tue Oct 03 11:46:58.047199 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435] Traceback (most recent call last):
[Tue Oct 03 11:46:58.047220 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]   File "/var/www/html/get5-web/get5.wsgi", line 15, in <module>
[Tue Oct 03 11:46:58.047284 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]     from get5 import app as application
[Tue Oct 03 11:46:58.047304 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]   File "/var/www/html/get5-web/get5/__init__.py", line 73, in <module>
[Tue Oct 03 11:46:58.047387 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]     app.config['LOG_PATH'], when='midnight')
[Tue Oct 03 11:46:58.047396 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]   File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
[Tue Oct 03 11:46:58.047662 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Tue Oct 03 11:46:58.047672 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
[Tue Oct 03 11:46:58.047686 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Tue Oct 03 11:46:58.047693 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]   File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
[Tue Oct 03 11:46:58.048014 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]     StreamHandler.__init__(self, self._open())
[Tue Oct 03 11:46:58.048024 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]   File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
[Tue Oct 03 11:46:58.048036 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435]     stream = open(self.baseFilename, self.mode)
[Tue Oct 03 11:46:58.048056 2017] [wsgi:error] [pid 23543] [client 79.225.106.113:62435] IOError: [Errno 13] Permission denied: '/var/www/html/get5-web/logs/get5.log'
[Tue Oct 03 11:46:58.100758 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436] mod_wsgi (pid=23542): Target WSGI script '/var/www/html/get5-web/get5.wsgi' cannot be loaded as Python module.
[Tue Oct 03 11:46:58.100803 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436] mod_wsgi (pid=23542): Exception occurred processing WSGI script '/var/www/html/get5-web/get5.wsgi'.
[Tue Oct 03 11:46:58.100832 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436] Traceback (most recent call last):
[Tue Oct 03 11:46:58.100848 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]   File "/var/www/html/get5-web/get5.wsgi", line 15, in <module>
[Tue Oct 03 11:46:58.100910 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]     from get5 import app as application
[Tue Oct 03 11:46:58.100919 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]   File "/var/www/html/get5-web/get5/__init__.py", line 73, in <module>
[Tue Oct 03 11:46:58.101017 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]     app.config['LOG_PATH'], when='midnight')
[Tue Oct 03 11:46:58.101032 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]   File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
[Tue Oct 03 11:46:58.101422 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Tue Oct 03 11:46:58.101435 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
[Tue Oct 03 11:46:58.101450 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Tue Oct 03 11:46:58.101458 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]   File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
[Tue Oct 03 11:46:58.101913 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]     StreamHandler.__init__(self, self._open())
[Tue Oct 03 11:46:58.101949 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]   File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
[Tue Oct 03 11:46:58.101968 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436]     stream = open(self.baseFilename, self.mode)
[Tue Oct 03 11:46:58.101988 2017] [wsgi:error] [pid 23542] [client 79.225.106.113:62436] IOError: [Errno 13] Permission denied: '/var/www/html/get5-web/logs/get5.log'
[Tue Oct 03 11:48:32.500456 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700] mod_wsgi (pid=23532): Target WSGI script '/var/www/html/get5-web/get5.wsgi' cannot be loaded as Python module.
[Tue Oct 03 11:48:32.500536 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700] mod_wsgi (pid=23532): Exception occurred processing WSGI script '/var/www/html/get5-web/get5.wsgi'.
[Tue Oct 03 11:48:32.500566 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700] Traceback (most recent call last):
[Tue Oct 03 11:48:32.500591 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]   File "/var/www/html/get5-web/get5.wsgi", line 15, in <module>
[Tue Oct 03 11:48:32.500688 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]     from get5 import app as application
[Tue Oct 03 11:48:32.500704 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]   File "/var/www/html/get5-web/get5/__init__.py", line 73, in <module>
[Tue Oct 03 11:48:32.500829 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]     app.config['LOG_PATH'], when='midnight')
[Tue Oct 03 11:48:32.500842 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]   File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
[Tue Oct 03 11:48:32.501252 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Tue Oct 03 11:48:32.501266 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
[Tue Oct 03 11:48:32.501281 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Tue Oct 03 11:48:32.501289 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]   File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
[Tue Oct 03 11:48:32.501772 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]     StreamHandler.__init__(self, self._open())
[Tue Oct 03 11:48:32.501785 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]   File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
[Tue Oct 03 11:48:32.501800 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700]     stream = open(self.baseFilename, self.mode)
[Tue Oct 03 11:48:32.501820 2017] [wsgi:error] [pid 23532] [client 79.225.106.113:58700] IOError: [Errno 13] Permission denied: '/var/www/html/get5-web/logs/get5.log'
