### ISSUE TITLE
Sorry, you don't have access to this webpanel

### ISSUE THREAD

**Issue by glockmaster** [splewis/get5-web#69]
Hi, 

I cant login to the webpanel after any errors on the instalattion. Now when im going to login with my steam account (ID64 added on the file) i get this error from log.

[Tue Oct 10 17:14:48.402843 2017] [mpm_prefork:notice] [pid 988] AH00163: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Tue Oct 10 17:14:48.402865 2017] [core:notice] [pid 988] AH00094: Command line: '/usr/sbin/apache2'
Missing required parameter in response from https://steamcommunity.com/openid/login: (u'http://specs.openid.net/auth/2.0', 'assoc_type')
Generated checkid_setup request to https://steamcommunity.com/openid/login using stateless mode.
Error attempting to use stored discovery information: <openid.consumer.consumer.TypeURIMismatch: Required type http://specs.openid.net/auth/2.0/signon not found in ['http://specs.openid.net/auth/2.0/server'] for endpoint <openid.consumer.discover.OpenIDServiceEndpoint server_url='https://steamcommunity.com/openid/login' claimed_id=None local_id=None canonicalID=None used_yadis=True >>
Attempting discovery to verify endpoint
Performing discovery on http://steamcommunity.com/openid/id/idhidden
Received id_res response from https://steamcommunity.com/openid/login using association 1234567890

Anyone knows hot to fix this???
Regards

**Comment by splewis** [comment]
Can you post your instance/prod_config.py file (with passwords and db info removed)?

**Comment by glockmaster** [comment]
##### You must change these before running
SQLALCHEMY_DATABASE_URI = 'mysql://user:password@localhost/get5'  # Sqlalchemy database connection info
STEAM_API_KEY = 'keyremoved'  # See https://steamcommunity.com/dev/apikey
SECRET_KEY = 'keyremoved'  # Secret key used for flask cookies

##### Everything below this line is optional to change

import os

location = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__), '..', 'logs'))
LOG_PATH = os.path.join(location, 'get5.log')

DEBUG = False
TESTING = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
USER_MAX_SERVERS = 10  # Max servers a user can create
USER_MAX_TEAMS = 100  # Max teams a user can create
USER_MAX_MATCHES = 1000  # Max matches a user can create
DEFAULT_PAGE = '/matches'
ADMINS_ACCESS_ALL_MATCHES = True  # Whether admins can always access any match admin panel
CREATE_MATCH_TITLE_TEXT = False # Whether settings for "match title text" and "team text" appear on "create a match page"

# All maps that are selectable in the "create a match" page
MAPLIST = [
    'de_cache',
    'de_cbble',
    'de_inferno',
    'de_mirage',
    'de_nuke',
    'de_overpass',
    'de_train',
    'de_dust2',
    'de_season',
]

# Maps whose checkbox is selected (in the mappool) by default in the "create a match" page
DEFAULT_MAPLIST = [
    'de_cache',
    'de_cbble',
    'de_inferno',
    'de_mirage',
    'de_nuke',
    'de_overpass',
    'de_train',
]

# You may set the server to allow allow whitelisted steamids to login.
# By default any user can login and create teams/servers/matches.
WHITELISTED_IDS = []

# Admins will have extra access to create "public" teams, and if ADMINS_ACCESS_ALL_MATCHES
# is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match.
ADMIN_IDS = []

**Comment by TandelK** [comment]
In the last Admin_IDS=[] you have add your SteamID 64. 
ADMIN_IDS = [
"STEAMID1"
"STEAMID2"
]

**Comment by splewis** [comment]
No, you should still have access without ADMIN_IDS being set: https://github.com/splewis/get5-web/blob/master/get5/__init__.py#L119

**Comment by splewis** [comment]
Closing since there's been no update here.
