### ISSUE TITLE
Add cvar setting support

### ISSUE THREAD

**Issue by splewis** [splewis/get5-web#7]
Most likely as strings only, with a configurable maximum number of cvars per match. Maybe a max name/length setting for the cvars themselves too.

**Comment by splewis** [comment]
The biggest impediment to me doing this is the UI. Probably requires javascripty stuff like a + button to reveal more fields to set. Which I have no idea how to do. (that same idea applied to the team section for putting in player steamids would be useful as well)

Probably best to either store the cvar data in pickled python data, either as a dictionary or list of (cvar, value) tuples.

**Comment by Technoblazed** [comment]
Not entirely sure how you'd want to implement something like this with a limit, but this would suffice:
```
<input type="button" id="ADD_MORE_PLAYERS" onclick="add_players();" value="Add Player" />
```

```
<script>
function add_players() {
   var d = document.getElementById("JUST_SOME_DIV_NAME_FOR_TEAMS");
   d.innerHTML += "WHATEVER_HTML_YOU_USE_FOR_TEAMS";
}
</script>
```

**Comment by splewis** [comment]
I don't think this is ever going to happen.
