### ISSUE TITLE
Config not applied?

### ISSUE THREAD

**Issue by FaNNboii** [splewis/get5-web#70]
Hey, when i create a Match over get5-web in the Server Log it says following:

command "get5_web_avaliable"
command "get5_loadmatch_url xxxx.xxxx/match/52/config"
command "get5_web_api_key XXXXXXXXXXXXXXXXXXXXX"

but when i type in: get_status it says:
{
             "gamestate": 0,
             "plugin_version": "0.5.3-dev+329",
             "gamestate_string": "none",
             "commit": "5e7162a",
             "paused": false
}

and when i try to join server it says "Disconnect: There is no match setup."
why? -.-

**Comment by splewis** [comment]
I need more information to help you.

Either a [debug dump](https://github.com/splewis/get5/wiki/Debugging-help#getting-a-debug-dump) (your version is probably to old, though), error logs on the server, or a reproducable get5_loadmatch_url  command.

**Comment by FaNNboii** [comment]
command "get5_web_avaliable"
command "get5_loadmatch_url get5.becher.xyz/match/57/config"
command "get5_web_api_key XXXXXXXX"

get5_status
rcon from "79.225.106.113:50709": command "get5_status"
{
    "gamestate": 0,
    "plugin_version": "0.5.4-dev+355",
    "gamestate_string": "none",
    "commit": "d48e98e",
    "paused": false
}
rcon from "79.225.106.113:50709": command "get5_status"
server_cvar: "nextlevel" "de_inferno"
get5_event: {
    "params": {
        "team1_name": "trololo",
        "team2_name": "senf"
    },
    "matchid": "57",
    "event": "series_start"
}
"trololo# x] * HvHTournament.cc<3><STEAM_1:1:7692104><>" connected, address ""
World triggered "Round_Start"
[META] Loaded 0 plugins (1 already loaded)
[META] Loaded 0 plugins (1 already loaded)
Log file started (file "logs/L137_074_231_091_27015_201710211552_000.log") (game "/home/csgoserver/serverfiles/csgo") (version "6878")
Loading map "de_inferno"
server cvars start
"cash_player_killed_teammate" = "-300"
"cash_player_respawn_amount" = "0"
"sv_maxspeed" = "320"
"sm_teamchange_unlimited_restrict_spec" = "0"
"cash_team_rescued_hostage" = "600"
"cash_team_win_by_defusing_bomb" = "3500"
"sv_rollangle" = "0"
"r_AirboatViewZHeight" = "0.0"
"sv_cheats" = "0"
Log file closed
"r_VehicleViewDampen" = "1"
"metamod_version" = "1.11.0-dev+1098V"
"mp_allowNPCs" = "1"
"mp_tournament" = "0"
"sv_vote_issue_pause_match_spec_only" = "0"
"sv_spec_hear" = "1"
"cash_player_interact_with_hostage" = "300"
"mp_maxrounds" = "30"
"mp_flashlight" = "0"
"sv_tags" = "Cheats,HvH,HvHTournament,HvHTournament.cc,insecure"
"sv_stepsize" = "18"
"sv_autobuyammo" = "0"
"sv_alltalk" = "0"
"sv_rollspeed" = "200"
"mp_teamlist" = "hgrunt;scientist"
"sm_weaponrestrict_version" = "1.0"
"mp_footsteps" = "1"
"sv_noclipaccelerate" = "5"
"sv_accelerate_debug_speed" = "0"
"sv_wateraccelerate" = "10"
"sm_teamchange_unlimited_roundlimit" = "0"
"mp_stalemate_enable" = "0"
"mp_autocrosshair" = "1"
"sourcemod_version" = "1.9.0.6154"
"cash_team_elimination_bomb_map" = "3250"
"cash_player_get_killed" = "0"
"mp_roundtime_defuse" = "1.92"
"mp_respawnwavetime" = "10.0"
"sv_teamid_overhead" = "1"
"tv_enable1" = "0"
"nextlevel" = "de_inferno"
"sv_stopspeed" = "80"
"sv_specaccelerate" = "5"
"deathmatch" = "1"
"sm_teamchange_unlimited_maplimit" = "0"
"tv_enable" = "1"
"sv_airaccelerate" = "12"
"mp_roundtime_hostage" = "1.92"
"sv_show_team_equipment_prohibit" = "0"
"mp_freezetime" = "15"
"mp_teams_unbalance_limit" = "1"
"mp_timelimit" = "0"
"cash_team_loser_bonus" = "1400"
"sv_deadtalk" = "1"
"sm_teamchange_unlimited_suicide" = "1"
"cash_player_rescued_hostage" = "1000"
"sv_waterfriction" = "1"
"sv_competitive_official_5v5" = "0"
"sv_steamgroup" = ""
"cash_player_killed_enemy_default" = "300"
"coop" = "0"
"cash_team_survive_guardian_wave" = "1000"
"tv_relaypassword" = ""
"sm_teamchange_unlimited_restrict_ct" = "0"
"mp_teamplay" = "0"
"mp_teammates_are_enemies" = "0"
"cash_team_terrorist_win_bomb" = "3500"
"cash_team_elimination_hostage_map_t" = "3000"
"mp_falldamage" = "0"
"r_JeepViewDampenFreq" = "7.0"
"sv_accelerate_use_weapon_speed" = "1"
"cash_team_win_by_time_running_out_hostage" = "3250"
"sv_specnoclip" = "1"
"sv_friction" = "5.2"
"sv_voiceenable" = "1"
"cash_player_bomb_planted" = "300"
"mp_autoteambalance" = "1"
"sv_contact" = ""
"sm_teamchange_unlimited_restrict_auto" = "0"
"sv_teamid_overhead_always_prohibit" = "0"
"sv_vote_kick_ban_duration" = "15"
"cash_player_bomb_defused" = "300"
"sv_bounce" = "0"
"mp_roundtime" = "1.92"
"mp_disable_respawn_times" = "0"
"sm_teamchange_unlimited_suicide_admin" = "1"
"r_AirboatViewDampenFreq" = "7.0"
"mp_weaponstay" = "0"
"sv_kick_ban_duration" = "15"
"cash_team_planted_bomb_but_defused" = "800"
"sm_teamchange_unlimited_version" = "1.2.2"
"cash_player_killed_hostage" = "-1000"
"sv_vote_issue_loadbackup_allowed" = "1"
"mp_hostagepenalty" = "10"
"tv_advertise_watchable" = "1"
"mp_friendlyfire" = "1"
"cash_team_hostage_interaction" = "600"
"nextmode" = ""
"sv_noclipspeed" = "5"
"mp_fraglimit" = "0"
"sm_teamchange_unlimited_restrict_t" = "0"
"cash_team_win_by_time_running_out_bomb" = "3250"
"mp_forcerespawn" = "1"
"sv_allchat" = "1"
"mp_winlimit" = "0"
"sv_accelerate" = "5.5"
"mp_buy_during_immunity" = "0"
"mp_buy_anywhere" = "0"
"cash_player_killed_enemy_factor" = "1"
"cash_team_elimination_hostage_map_ct" = "3000"
"sv_gravity" = "800"
"mp_c4timer" = "40"
"cash_team_win_by_hostage_rescue" = "2900"
"sm_teamchange_unlimited_immunity" = "0"
"sv_vote_issue_loadbackup_spec_only" = "0"
"r_JeepViewDampenDamp" = "1.0"
"sv_password" = "1337"
"cash_team_loser_bonus_consecutive_rounds" = "500"
"sv_competitive_minspec" = "1"
"cash_player_damage_hostage" = "-30"
"r_AirboatViewDampenDamp" = "1.0"
"r_JeepViewZHeight" = "10.0"
"cash_team_hostage_alive" = "0"
"sm_nextmap" = "de_inferno"
"tv_password" = ""
"get5_version" = "0.5.4-dev+355"
"sv_max_allowed_net_graph" = "1"
"mp_stalemate_at_timelimit" = "0"
"sv_specspeed" = "3"
"sm_teamchange_unlimited_chat" = "1"
"mp_limitteams" = "2"
server cvars end
"sv_footsteps" = "1"
"sv_vote_issue_kick_allowed" = "1"
logaddress_add "79.225.106.113:7130"
Started map "de_inferno" (CRC "-948999917")
server_cvar: "cash_player_interact_with_hostage" "150"
server_cvar: "cash_team_elimination_hostage_map_ct" "2000"
server_cvar: "cash_team_elimination_hostage_map_t" "1000"
server_cvar: "cash_team_hostage_interaction" "500"
server_cvar: "cash_team_rescued_hostage" "0"
server_cvar: "cash_team_win_by_defusing_bomb" "3250"
server_cvar: "cash_team_win_by_hostage_rescue" "3500"
server_cvar: "mp_freezetime" "6"
server_cvar: "mp_friendlyfire" "0"
server_cvar: "mp_maxrounds" "0"
server_cvar: "mp_roundtime" "5"
server_cvar: "mp_roundtime_defuse" "0"
server_cvar: "sv_deadtalk" "0"
server_cvar: "mp_roundtime_hostage" "0"
server_cvar: "mp_timelimit" "5"
server_cvar: "nextlevel" ""
server_cvar: "sm_nextmap" "de_nuke"
server_cvar: "mp_autoteambalance" "0"
server_cvar: "mp_limitteams" "0"
server_cvar: "mp_timelimit" "0"
server_cvar: "sv_alltalk" "1"
server_cvar: "sv_competitive_official_5v5" "1"
server_cvar: "sv_deadtalk" "1"
Starting Freeze period
World triggered "Match_Start" on "de_inferno"


So i create a Match on get5-web and it apply on Server. When i try to join ther Server in Console only stays: 
Connecting to public(137.74.231.91:27015) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
Connecting to public(137.74.231.91:27015) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
Connected to 137.74.231.91:27015

cant connect. then i disconnect through console and try to join again then it says: Disconnect: There is no match setup.

so when i try to join the first time it seems that the server crashes and restart and thats because there is no match setup anymore..

any help?

**Comment by FaNNboii** [comment]
SourceMod Version Information:
    SourceMod Version: 1.9.0.6154
    SourcePawn Engine: 1.9.0.6154, jit-x86 (build 1.9.0.6154)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Sep 19 2017 15:29:05
    Built from: https://github.com/alliedmodders/sourcemod/commit/4e996a1
    Build ID: 6154:4e996a1
    http://www.sourcemod.net/

"get5_version" = "0.5.4-dev+355" notify singleplayer replicated                  - Current get5 version


now i added get5_debug 32 in get5.cfg and now it says on get5-web when i try to create a match:
Failed to load match configs on server

and in debug.log:
L 10/21/2017 - 16:01:58: [get5] cleanedUrl (system2) = get5.becher.xyz/match/58/config
L 10/21/2017 - 16:01:58: [get5_api] get5_web_api_url now set to 
L 10/21/2017 - 16:02:28: [get5] cleanedUrl (system2) = get5.becher.xyz/match/59/config
L 10/21/2017 - 16:02:28: [get5_api] get5_web_api_url now set to

**Comment by splewis** [comment]
I'm closing and locking this for a few reasons:

- Adding information then deleting it makes it impossible to help users
- When i ran get5_loadmatch on get5@d48e98e7a25eaaf3d3c965888ed60f041dc638ba with the match config in the url, it loaded fine.
- The info added had ``"sv_tags" = "Cheats,HvH,HvHTournament,HvHTournament.cc,insecure"``. That's stupid. I'm not spending any more time supporting that.
