### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Mrciller** [splewis/get5-web#73]
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at sean@splewis.net to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by Mrciller** [comment]
root@cillerian:/var/www/get5-web# ./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/get5-web/get5/__init__.py", line 26, in <module>
    import steamid
  File "/var/www/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id

**Comment by Technoblazed** [comment]
Did you follow the installation requirements?

**Comment by Mrciller** [comment]
yes

**Comment by Technoblazed** [comment]
`valve.steam.id` is installed when you run `pip install -r requirements.txt`

**Comment by Mrciller** [comment]
root@cillerian:/var/www/get5-web# apt install python-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all python-all-dev python-dev python-setuptools python-wheel python2.7-dev
Suggested packages:
  python-setuptools-doc
The following NEW packages will be installed:
  libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all python-all-dev python-dev python-pip python-setuptools python-wheel python2.7-dev
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.6 MB of archives.
After this operation, 43.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://at.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libexpat1-dev amd64 2.1.0-7ubuntu0.16.04.3 [115 kB]
Get:2 http://at.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython2.7-dev amd64 2.7.12-1ubuntu0~16.04.2 [27.8 MB]
Get:3 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 libpython-dev amd64 2.7.11-1 [7728 B]
Get:4 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 libpython-all-dev amd64 2.7.11-1 [992 B]
Get:5 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 python-all amd64 2.7.11-1 [978 B]
Get:6 http://at.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python2.7-dev amd64 2.7.12-1ubuntu0~16.04.2 [276 kB]
Get:7 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 python-dev amd64 2.7.11-1 [1160 B]
Get:8 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 python-all-dev amd64 2.7.11-1 [1000 B]
Get:9 http://at.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python-pip all 8.1.1-2ubuntu0.4 [144 kB]
Get:10 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 python-setuptools all 20.7.0-1 [169 kB]
Get:11 http://at.archive.ubuntu.com/ubuntu xenial/universe amd64 python-wheel all 0.29.0-1 [48.0 kB]
Fetched 28.6 MB in 0s (38.7 MB/s)
Selecting previously unselected package libexpat1-dev:amd64.
(Reading database ... 132092 files and directories currently installed.)
Preparing to unpack .../libexpat1-dev_2.1.0-7ubuntu0.16.04.3_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Selecting previously unselected package libpython2.7-dev:amd64.
Preparing to unpack .../libpython2.7-dev_2.7.12-1ubuntu0~16.04.2_amd64.deb ...
Unpacking libpython2.7-dev:amd64 (2.7.12-1ubuntu0~16.04.2) ...
Selecting previously unselected package libpython-dev:amd64.
Preparing to unpack .../libpython-dev_2.7.11-1_amd64.deb ...
Unpacking libpython-dev:amd64 (2.7.11-1) ...
Selecting previously unselected package libpython-all-dev:amd64.
Preparing to unpack .../libpython-all-dev_2.7.11-1_amd64.deb ...
Unpacking libpython-all-dev:amd64 (2.7.11-1) ...
Selecting previously unselected package python-all.
Preparing to unpack .../python-all_2.7.11-1_amd64.deb ...
Unpacking python-all (2.7.11-1) ...
Selecting previously unselected package python2.7-dev.
Preparing to unpack .../python2.7-dev_2.7.12-1ubuntu0~16.04.2_amd64.deb ...
Unpacking python2.7-dev (2.7.12-1ubuntu0~16.04.2) ...
Selecting previously unselected package python-dev.
Preparing to unpack .../python-dev_2.7.11-1_amd64.deb ...
Unpacking python-dev (2.7.11-1) ...
Selecting previously unselected package python-all-dev.
Preparing to unpack .../python-all-dev_2.7.11-1_amd64.deb ...
Unpacking python-all-dev (2.7.11-1) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../python-pip_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python-pip (8.1.1-2ubuntu0.4) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../python-setuptools_20.7.0-1_all.deb ...
Unpacking python-setuptools (20.7.0-1) ...
Selecting previously unselected package python-wheel.
Preparing to unpack .../python-wheel_0.29.0-1_all.deb ...
Unpacking python-wheel (0.29.0-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Setting up libpython2.7-dev:amd64 (2.7.12-1ubuntu0~16.04.2) ...
Setting up libpython-dev:amd64 (2.7.11-1) ...
Setting up libpython-all-dev:amd64 (2.7.11-1) ...
Setting up python-all (2.7.11-1) ...
Setting up python2.7-dev (2.7.12-1ubuntu0~16.04.2) ...
Setting up python-dev (2.7.11-1) ...
Setting up python-all-dev (2.7.11-1) ...
Setting up python-pip (8.1.1-2ubuntu0.4) ...
Setting up python-setuptools (20.7.0-1) ...
Setting up python-wheel (0.29.0-1) ...
root@cillerian:/var/www/get5-web# pip install -r requirements.txt
Collecting alembic==0.8.6 (from -r requirements.txt (line 1))
  Using cached alembic-0.8.6.tar.gz
Collecting astroid==1.4.5 (from -r requirements.txt (line 2))
  Using cached astroid-1.4.5-py2.py3-none-any.whl
Collecting autopep8==1.2.4 (from -r requirements.txt (line 3))
  Using cached autopep8-1.2.4-py2.py3-none-any.whl
Collecting blinker==1.4 (from -r requirements.txt (line 4))
  Using cached blinker-1.4.tar.gz
Collecting colorama==0.3.7 (from -r requirements.txt (line 5))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting configparser==3.5.0 (from -r requirements.txt (line 6))
  Using cached configparser-3.5.0.tar.gz
Collecting coverage==4.1 (from -r requirements.txt (line 7))
  Using cached coverage-4.1.tar.gz
Collecting docopt==0.6.2 (from -r requirements.txt (line 8))
  Using cached docopt-0.6.2.tar.gz
Collecting enum==0.4.6 (from -r requirements.txt (line 9))
  Using cached enum-0.4.6.tar.gz
Collecting enum34==1.1.6 (from -r requirements.txt (line 10))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting flake8==3.2.1 (from -r requirements.txt (line 11))
  Using cached flake8-3.2.1-py2.py3-none-any.whl
Collecting Flask==0.10.1 (from -r requirements.txt (line 12))
  Using cached Flask-0.10.1.tar.gz
Collecting Flask-Assets==0.11 (from -r requirements.txt (line 13))
  Using cached Flask-Assets-0.11.tar.gz
Collecting Flask-Cache==0.13.1 (from -r requirements.txt (line 14))
  Using cached Flask-Cache-0.13.1.tar.gz
Collecting Flask-Limiter==0.9.3 (from -r requirements.txt (line 15))
  Using cached Flask-Limiter-0.9.3.tar.gz
Collecting Flask-Migrate==1.8.0 (from -r requirements.txt (line 16))
  Using cached Flask-Migrate-1.8.0.tar.gz
Collecting Flask-MySQL==1.3 (from -r requirements.txt (line 17))
  Using cached Flask_MySQL-1.3-py2.py3-none-any.whl
Collecting Flask-OpenID==1.2.5 (from -r requirements.txt (line 18))
  Using cached Flask-OpenID-1.2.5.tar.gz
Collecting Flask-Script==2.0.5 (from -r requirements.txt (line 19))
  Using cached Flask-Script-2.0.5.tar.gz
Collecting Flask-SQLAlchemy==2.1 (from -r requirements.txt (line 20))
  Using cached Flask-SQLAlchemy-2.1.tar.gz
Collecting Flask-Testing==0.4.2 (from -r requirements.txt (line 21))
  Using cached Flask-Testing-0.4.2.tar.gz
Collecting Flask-Uploads==0.2.1 (from -r requirements.txt (line 22))
  Using cached Flask-Uploads-0.2.1.tar.gz
Collecting Flask-WTF==0.12 (from -r requirements.txt (line 23))
  Using cached Flask_WTF-0.12-py2-none-any.whl
Collecting itsdangerous==0.24 (from -r requirements.txt (line 24))
  Using cached itsdangerous-0.24.tar.gz
Collecting Jinja2==2.8 (from -r requirements.txt (line 25))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.2.2 (from -r requirements.txt (line 26))
  Using cached lazy_object_proxy-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting limits==1.1.1 (from -r requirements.txt (line 27))
  Using cached limits-1.1.1.tar.gz
Collecting Mako==1.0.4 (from -r requirements.txt (line 28))
  Using cached Mako-1.0.4.tar.gz
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 29))
  Using cached MarkupSafe-0.23.tar.gz
Collecting mccabe==0.5.2 (from -r requirements.txt (line 30))
  Using cached mccabe-0.5.2-py2.py3-none-any.whl
Collecting monotonic==1.1 (from -r requirements.txt (line 31))
  Using cached monotonic-1.1-py2.py3-none-any.whl
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 32))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-31zjA7/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-31zjA7/MySQL-python/setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-31zjA7/MySQL-python/setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-31zjA7/MySQL-python/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Technoblazed** [comment]
```
apt-get install libmysqlclient-dev
```

Then rerun the pip command

**Comment by Mrciller** [comment]
i did now it worked, but still 500 Internal Server Error (on web browser)

**Comment by Technoblazed** [comment]
Check your apache error logs then, I've never used get5-web with apache so I'm no help to you. It's likely that your WSGI isn't configured correctly, in which case, have a skim through https://github.com/splewis/get5-web/issues/43

**Comment by Mrciller** [comment]
get5.wsgi is correctly configured but i think that wsgi isnt installed how can i see that it is installed?

**Comment by Technoblazed** [comment]
Can you post your `/var/www/get5-/web/get5.wsgi` and `/etc/apache/sites-available/<whateveryoursiscalled>`

**Comment by Mrciller** [comment]
#!/usr/bin/python

activate_this = '/var/www/html/get5-web/venv/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import sys
import logging
logging.basicConfig(stream=sys.stderr)

folder = "/var/www/html/get5-web"
if not folder in sys.path:
    sys.path.insert(0, folder)
sys.path.insert(0,"")

from get5 import app as application
import get5
get5.register_blueprints()

**Comment by Mrciller** [comment]
<VirtualHost *:80>
		ServerName get5.splewis.net
		ServerAdmin sean@splewis.net
		WSGIScriptAlias / /var/www/get5-web/get5.wsgi

		<Directory /var/www/get5>
			Order deny,allow
			Allow from all
		</Directory>

		Alias /static /var/www/get5-web/get5/static
		<Directory /var/www/get5-web/get5/static>
			Order allow,deny
			Allow from all
		</Directory>

		ErrorLog ${APACHE_LOG_DIR}/error.log
		LogLevel warn
		CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by Technoblazed** [comment]
Do you have any errors inside your apache error logs?

**Comment by Mrciller** [comment]
[Mon Dec 11 12:10:27.114677 2017] [wsgi:warn] [pid 2537] mod_wsgi: Compiled for Python/2.7.11.
[Mon Dec 11 12:10:27.114749 2017] [wsgi:warn] [pid 2537] mod_wsgi: Runtime using Python/2.7.12.
[Mon Dec 11 12:10:27.119168 2017] [mpm_prefork:notice] [pid 2537] AH00163: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Mon Dec 11 12:10:27.119224 2017] [core:notice] [pid 2537] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 11 12:10:41.669649 2017] [wsgi:error] [pid 2540] [client 91.227.128.1:59005] mod_wsgi (pid=2540): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Mon Dec 11 12:10:41.669704 2017] [wsgi:error] [pid 2540] [client 91.227.128.1:59005] mod_wsgi (pid=2540): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Mon Dec 11 12:10:41.669721 2017] [wsgi:error] [pid 2540] [client 91.227.128.1:59005] Traceback (most recent call last):
[Mon Dec 11 12:10:41.669738 2017] [wsgi:error] [pid 2540] [client 91.227.128.1:59005]   File "/var/www/get5-web/get5.wsgi", line 4, in <module>
[Mon Dec 11 12:10:41.669780 2017] [wsgi:error] [pid 2540] [client 91.227.128.1:59005]     execfile(activate_this, dict(__file__=activate_this))
[Mon Dec 11 12:10:41.669797 2017] [wsgi:error] [pid 2540] [client 91.227.128.1:59005] IOError: [Errno 2] No such file or directory: '/var/www/html/get5-web/venv/bin/activate_this.py'

**Comment by Technoblazed** [comment]
Did you run 

```
virtualenv venv
source venv/bin/activate
```

When you were installing

**Comment by Mrciller** [comment]
yes i did

**Comment by Mrciller** [comment]
i didnt but a secret cookie key in is that the problem?

**Comment by Technoblazed** [comment]
The venv doesn't exist so it won't activate the wsgi script

**Comment by Mrciller** [comment]
root@cillerian:/var/www/get5-web# virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /var/www/get5-web/venv/bin/python2
Not overwriting existing python script /var/www/get5-web/venv/bin/python (you must use /var/www/get5-web/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.
Overwriting /var/www/get5-web/venv/bin/activate with new content
Overwriting /var/www/get5-web/venv/bin/activate.fish with new content
Overwriting /var/www/get5-web/venv/bin/activate.csh with new content
Overwriting /var/www/get5-web/venv/bin/python-config with new content
root@cillerian:/var/www/get5-web# source venv/bin/activate

**Comment by Mrciller** [comment]
/var/www/get5-web/venv/bin/ is the activate_this.py

**Comment by Mrciller** [comment]
i fixed the old one but now i have [Mon Dec 11 12:36:02.984066 2017] [wsgi:warn] [pid 2074] mod_wsgi: Compiled for Python/2.7.11.
[Mon Dec 11 12:36:02.984128 2017] [wsgi:warn] [pid 2074] mod_wsgi: Runtime using Python/2.7.12.
[Mon Dec 11 12:36:02.988185 2017] [mpm_prefork:notice] [pid 2074] AH00163: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Mon Dec 11 12:36:02.988236 2017] [core:notice] [pid 2074] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 11 12:36:12.075600 2017] [wsgi:error] [pid 2078] [client 91.227.128.1:53536] mod_wsgi (pid=2078): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Mon Dec 11 12:36:12.075656 2017] [wsgi:error] [pid 2078] [client 91.227.128.1:53536] mod_wsgi (pid=2078): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Mon Dec 11 12:36:12.075676 2017] [wsgi:error] [pid 2078] [client 91.227.128.1:53536] Traceback (most recent call last):
[Mon Dec 11 12:36:12.075695 2017] [wsgi:error] [pid 2078] [client 91.227.128.1:53536]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>
[Mon Dec 11 12:36:12.075745 2017] [wsgi:error] [pid 2078] [client 91.227.128.1:53536]     from get5 import app as application
[Mon Dec 11 12:36:12.075764 2017] [wsgi:error] [pid 2078] [client 91.227.128.1:53536] ImportError: No module named get5

**Comment by Mrciller** [comment]
ok now i resetupt my root-server and now i have debian 9 and this happens .



(venv) root@cillerian:/var/www/html/get5-web# virtualenv venv
Running virtualenv with interpreter /var/www/html/get5-web/venv/bin/python2
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 946, in create_env                                         ironment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/var/www/html/get5-web/venv/lib/python2.7/posixpath.py", line 360, in                                          abspath
    if not isabs(path):
  File "/var/www/html/get5-web/venv/lib/python2.7/posixpath.py", line 54, in i                                         sabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
(venv) root@cillerian:/var/www/html/get5-web# source venv/bin/activate
(venv) root@cillerian:/var/www/html/get5-web# sudo virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /var/www/html/get5-web/venv/bin/python2
Not overwriting existing python script /var/www/html/get5-web/venv/bin/python                                          (you must use /var/www/html/get5-web/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.
(venv) root@cillerian:/var/www/html/get5-web# source venv/bin/activate
(venv) root@cillerian:/var/www/html/get5-web# pip install -r requirements.txt
Requirement already satisfied: alembic==0.8.6 in ./venv/lib/python2.7/site-pac                                         kages (from -r requirements.txt (line 1))
Requirement already satisfied: astroid==1.4.5 in ./venv/lib/python2.7/site-pac                                         kages (from -r requirements.txt (line 2))
Requirement already satisfied: autopep8==1.2.4 in ./venv/lib/python2.7/site-pa                                         ckages (from -r requirements.txt (line 3))
Requirement already satisfied: blinker==1.4 in ./venv/lib/python2.7/site-packa                                         ges (from -r requirements.txt (line 4))
Requirement already satisfied: colorama==0.3.7 in ./venv/lib/python2.7/site-pa                                         ckages (from -r requirements.txt (line 5))
Requirement already satisfied: configparser==3.5.0 in ./venv/lib/python2.7/sit                                         e-packages (from -r requirements.txt (line 6))
Requirement already satisfied: coverage==4.1 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 7))
Requirement already satisfied: docopt==0.6.2 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 8))
Requirement already satisfied: enum==0.4.6 in ./venv/lib/python2.7/site-packag                                         es (from -r requirements.txt (line 9))
Requirement already satisfied: enum34==1.1.6 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 10))
Requirement already satisfied: flake8==3.2.1 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 11))
Requirement already satisfied: Flask==0.10.1 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 12))
Requirement already satisfied: Flask-Assets==0.11 in ./venv/lib/python2.7/site                                         -packages (from -r requirements.txt (line 13))
Requirement already satisfied: Flask-Cache==0.13.1 in ./venv/lib/python2.7/sit                                         e-packages (from -r requirements.txt (line 14))
Requirement already satisfied: Flask-Limiter==0.9.3 in ./venv/lib/python2.7/si                                         te-packages (from -r requirements.txt (line 15))
Requirement already satisfied: Flask-Migrate==1.8.0 in ./venv/lib/python2.7/si                                         te-packages (from -r requirements.txt (line 16))
Collecting Flask-MySQL==1.3 (from -r requirements.txt (line 17))
  Using cached Flask_MySQL-1.3-py2.py3-none-any.whl
Collecting Flask-OpenID==1.2.5 (from -r requirements.txt (line 18))
Requirement already satisfied: Flask-Script==2.0.5 in ./venv/lib/python2.7/sit                                         e-packages (from -r requirements.txt (line 19))
Requirement already satisfied: Flask-SQLAlchemy==2.1 in ./venv/lib/python2.7/s                                         ite-packages (from -r requirements.txt (line 20))
Collecting Flask-Testing==0.4.2 (from -r requirements.txt (line 21))
Collecting Flask-Uploads==0.2.1 (from -r requirements.txt (line 22))
Collecting Flask-WTF==0.12 (from -r requirements.txt (line 23))
  Using cached Flask_WTF-0.12-py2-none-any.whl
Requirement already satisfied: itsdangerous==0.24 in ./venv/lib/python2.7/site                                         -packages (from -r requirements.txt (line 24))
Requirement already satisfied: Jinja2==2.8 in ./venv/lib/python2.7/site-packag                                         es (from -r requirements.txt (line 25))
Requirement already satisfied: lazy-object-proxy==1.2.2 in ./venv/lib/python2.                                         7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: limits==1.1.1 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 27))
Requirement already satisfied: Mako==1.0.4 in ./venv/lib/python2.7/site-packag                                         es (from -r requirements.txt (line 28))
Requirement already satisfied: MarkupSafe==0.23 in ./venv/lib/python2.7/site-p                                         ackages (from -r requirements.txt (line 29))
Requirement already satisfied: mccabe==0.5.2 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 30))
Collecting monotonic==1.1 (from -r requirements.txt (line 31))
  Using cached monotonic-1.1-py2.py3-none-any.whl
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 32))
  Using cached MySQL-python-1.2.5.zip
Requirement already satisfied: pep8==1.7.0 in ./venv/lib/python2.7/site-packag                                         es (from -r requirements.txt (line 33))
Requirement already satisfied: pycodestyle==2.2.0 in ./venv/lib/python2.7/site                                         -packages (from -r requirements.txt (line 34))
Requirement already satisfied: pyflakes==1.2.3 in ./venv/lib/python2.7/site-pa                                         ckages (from -r requirements.txt (line 35))
Collecting pylint==1.5.5 (from -r requirements.txt (line 36))
  Using cached pylint-1.5.5-py2.py3-none-any.whl
Requirement already satisfied: python-editor==1.0 in ./venv/lib/python2.7/site                                         -packages (from -r requirements.txt (line 37))
Collecting python-openid==2.2.5 (from -r requirements.txt (line 38))
Collecting python-valve==0.1.1 (from -r requirements.txt (line 39))
Collecting requests==2.10.0 (from -r requirements.txt (line 40))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in ./venv/lib/python2.7/site-packag                                         es (from -r requirements.txt (line 41))
Requirement already satisfied: SQLAlchemy==1.0.13 in ./venv/lib/python2.7/site                                         -packages (from -r requirements.txt (line 42))
Requirement already satisfied: webassets==0.11.1 in ./venv/lib/python2.7/site-                                         packages (from -r requirements.txt (line 43))
Requirement already satisfied: Werkzeug==0.11.9 in ./venv/lib/python2.7/site-p                                         ackages (from -r requirements.txt (line 44))
Requirement already satisfied: wrapt==1.10.8 in ./venv/lib/python2.7/site-pack                                         ages (from -r requirements.txt (line 45))
Collecting WTForms==2.1 (from -r requirements.txt (line 46))
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-package                                         s (from enum==0.4.6->-r requirements.txt (line 9))
Building wheels for collected packages: MySQL-python
  Running setup.py bdist_wheel for MySQL-python ... error
  Complete output from command /var/www/html/get5-web/venv/bin/python2 -u -c "                                         import setuptools, tokenize;__file__='/tmp/pip-build-ejZJwn/MySQL-python/setup                                         .py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',                                          '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tm                                         pMDDcCupip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb
  copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb
  creating build/lib.linux-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb/                                         constants
  copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/consta                                         nts
  copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQLd                                         b/constants
  copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/consta                                         nts
  copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/cons                                         tants
  copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/c                                         onstants
  copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/co                                         nstants
  running build_ext
  building '_mysql' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototy                                         pes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map                                         =/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-se                                         curity -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/inclu                                         de/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_                                         mysql.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for MySQL-python
  Running setup.py clean for MySQL-python
Failed to build MySQL-python
Installing collected packages: MySQL-python, Flask-MySQL, python-openid, Flask                                         -OpenID, Flask-Testing, Flask-Uploads, WTForms, Flask-WTF, monotonic, pylint,                                          requests, python-valve
  Running setup.py install for MySQL-python ... error
    Complete output from command /var/www/html/get5-web/venv/bin/python2 -u -c                                          "import setuptools, tokenize;__file__='/tmp/pip-build-ejZJwn/MySQL-python/set                                         up.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n                                         ', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tm                                         p/pip-AzCcXv-record/install-record.txt --single-version-externally-managed --c                                         ompile --install-headers /var/www/html/get5-web/venv/include/site/python2.7/My                                         SQL-python:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb
    creating build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-2.7/MySQLd                                         b/constants
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/cons                                         tants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQ                                         Ldb/constants
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/cons                                         tants
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/co                                         nstants
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb                                         /constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/                                         constants
    running build_ext
    building '_mysql' extension
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-proto                                         types -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-m                                         ap=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-                                         security -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/inc                                         lude/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7                                         /_mysql.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/var/www/html/get5-web/venv/bin/python2 -u -c "import setuptools, tok                                         enize;__file__='/tmp/pip-build-ejZJwn/MySQL-python/setup.py';f=getattr(tokeniz                                         e, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(                                         compile(code, __file__, 'exec'))" install --record /tmp/pip-AzCcXv-record/inst                                         all-record.txt --single-version-externally-managed --compile --install-headers                                          /var/www/html/get5-web/venv/include/site/python2.7/MySQL-python" failed with                                          error code 1 in /tmp/pip-build-ejZJwn/MySQL-python/

**Comment by Mrciller** [comment]
fixed it on my own

**Comment by SHaenk** [comment]
How you fixed this?

**Comment by Technoblazed** [comment]
I’m going to write a complete install guide for get5 tonight, this is ridiculous

**Comment by splewis** [comment]
https://xkcd.com/979/
