### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by Mrciller** [splewis/get5-web#77]
I cant add a Server in the Website it always says : Failed to connect to server

I think that rcon is the problem.

My start settings are :  screen ./srcds_run -tickrate 128 +sv_setsteamaccount myserverkey +exec server.cfg -usercon -port 27015 +rcon_password "password"

**Comment by Technoblazed** [comment]
Wouldn't recommend using `rcon_password` on the command line anyway, put it in your server.cfg

**Comment by Mrciller** [comment]
ok i put it in the server.cfg and started the server still same error on the website

**Comment by Technoblazed** [comment]
Add me on steam https://steamcommunity.com/id/Technoblazed . If we find the issue I'll post the solution here.

**Comment by Mrciller** [comment]
your friend list ist full XD

**Comment by Technoblazed** [comment]
![Image](https://i.tech-no.me/191217133333.png)

Nope.

**Comment by Technoblazed** [comment]
Issue was an incomplete command line. If you need help with command lines, check out the cs:go dedicated server page: https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers
