### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by YETIonPC** [splewis/get5-web#79]
is it possible to play workshop maps with the Webinterface. If yes can u say it how to add the Maps in the prod_config.py file?

PS: Overall a realy nice Plugin 🗡 

Best regards

**Comment by Technoblazed** [comment]
You should just need to use the relative paths, so in the maplist section of the prod_config.py, use `workshop/xxxxxxx/mapname` etc. 

I’d assume this is how it works, make sure you don’t have a .bsp name on the end and just the raw mapname, let me know if this works :^)

**Comment by YETIonPC** [comment]
Jap it works. You have to start your map first with the command host_workshop_map XXXXX and after that the server downloads the map and you can add the command like you explaned it. But you have to look in the console for the right mapname. :D

**Comment by Technoblazed** [comment]
To be honest, I’m pretty sure csgo supports starting workshop maps without the prefix, so you’d probably be able to just use the normal map format. Check out the valve workshop guide and setup the subscribed items section on your server and you won’t need to run that command
