### ISSUE TITLE
[Feature] Typo "TeamName" without create team. [via Create a Match]

### ISSUE THREAD

**Issue by MikkelDK** [splewis/get5-web#81]
Hi,

I'm missing a feature on get5-web, where it's possible to "typo" teamname/choose flag(location)
Without needed to "create a team" on each random teams.

is there some way, to do the "easier" way, without to using "create a team" ?

Thanks.

**Comment by Technoblazed** [comment]
To my knowledge, get5-web isn't really there to specify one team and not specify the other one, it seems like more of a tournament system to me.

**Comment by MikkelDK** [comment]
I understand @Technoblazed - but i was thinking, about it "could" be possible (as example) for scrims/matches, without it needed to be tournaments.

**Comment by splewis** [comment]
I'm not going to support match creation without creating teams. It would require too much restructuring for what I don't consider a useful feature.
