### ISSUE TITLE
_mysql_exceptions.OperationalError

### ISSUE THREAD

**Issue by SyMiRychi** [splewis/get5-web#82]
When they want to join the site, this is what it says: "Sorry, unexpected error: (_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'host' (0)")"
Can someone find a solution to this??

So, thanks :)

**Comment by Technoblazed** [comment]
I mean it’s pretty clear, the host segment of the database connection in your config is incorrect.

**Comment by splewis** [comment]
Check instance/prod_config.py

Some part of SQLALCHEMY_DATABASE_URI is probably incorrect.

**Comment by splewis** [comment]
Closing since there's been no update here.
