### ISSUE TITLE
Team logo list not populating

### ISSUE THREAD

**Issue by AlthalusAvan** [splewis/get5-web#83]
On my current installation of the Get5 Web Panel I've placed several files (use the example of ice.png) in the /get5/static/img/logos/ directory. My understanding of the functionality is that once the file is placed here, I should be able to use this file as the logo image for a team when on the Edit Team or Create Team page (i.e. ice or ice.png should appear as an option in the logo drop down menu), and that I should then load the same file into the /resource/flash/econ/tournaments/teams directory on my server.

The list in the web is not populating for me regardless of what file is placed within.

My only idea myself was that this could be a permissions issue, so I tried chown www-data on the directory and files within, to no effect.

**Comment by splewis** [comment]
Your understanding is right.

The web server reads that logos directory on startup though, so if you haven't restarted the process then you won't get the logos to show up yet. I'd try restarting the web server then testing again.

**Comment by AlthalusAvan** [comment]
Yep, that does it. I'll investigate if there's an elegant way to refresh without a web client restart, and if not I'll see about contributing documentation.
