### ISSUE TITLE
ADMIN ID, unsure if working, unsure how to change

### ISSUE THREAD

**Issue by splewis** [splewis/get5-web#84]
_From @BloodyIron on February 19, 2018 2:53_

I'm setting up for a LAN, and I'm seeing a couple small problems:

1. The ADMIN IDs and WHITELIST IDs don't seem to be honoured.
2. I'm not sure on how to change the STEAM64 IDs used for ADMIN IDs and WHITELIST IDs

Based on the documentation ( https://github.com/splewis/get5-web/blob/master/INSTALL.md ), it seems I need to change to the instance folder and modify prod_config.py, then go down a folder and run "
./manager.py db upgrade", however it _feels_ like this isn't being honoured.

Can I get some direction here? Or maybe it's not working?

I tried to intentionally not list my STEAMID in the list, but still have a valid STAEMID in the list (a friend's), so that my user should be unable to make a team, or stuff like that, but I was able to make a team. This is after running that upgrade string, and also restarting apache2.

So, I'm at a loss as to what I'm doing wrong. Or is this a bug?

_Copied from original issue: splewis/get5#230_

**Comment by BloodyIron** [comment]
Oops, my bad on wrong repo!

**Comment by splewis** [comment]
Your understanding is mostly correct (you don't need to run the db upgrade for a config change). 

I can't reproduce any issues though.

**Comment by BloodyIron** [comment]
I think that it might actually be working without me being sure. If we could have the documentation adjusted so we know the correct way to update the IDs lists that would be appreciated! I'm just really not sure which are the right steps, and which are extra, or whatever. :)

**Comment by Technoblazed** [comment]
@BloodyIron I'm not entirely sure what's the issue with the documentation, if you could be more specific about the issues that would be great.

**Comment by BloodyIron** [comment]
@Technoblazed the issue is when I want to modify the ADMIN/WHITELIST IDs. The documentation talks about what to do when you first set it up, but not _exactly_ which steps to take when you want to modify that list. I'm not sure if I should just edit the file and it'll get updated, or if I need to run commands after, or what. I think saying that explicitly in the documentation would help. :)

**Comment by splewis** [comment]
Looks like this is resolved.

Anyone is free to submit a PR for the documentation.
