### ISSUE TITLE
Custom configs, or series types

### ISSUE THREAD

**Issue by BloodyIron** [splewis/get5-web#85]
I can't seem to figure out how to run our own configs, or redefine series types. For tournaments it would be great for us to be able to have the server config on the get5-web instance, and have that feed to the CSGO servers. Plus if we could use this tool to do other fun stuff like Arms Race that would be sweet too.

I've poked all over, and can't find how to do this, is this possible?

**Comment by splewis** [comment]
You can't. Forking get5-web to set get5_live_cfg in the match configs is probably the easiest way.

**Comment by BloodyIron** [comment]
I couldn't for the life of me find where the configs that get5-web uses are stored, where would I find them?

**Comment by Technoblazed** [comment]
Modify here: https://github.com/splewis/get5-web/blob/ef2a6ed00da772c57135af389d5af457bc898d07/get5/models.py#L413 and add `d['cvars']['get5_live_cfg'] = 'somecfgname'`

**Comment by BloodyIron** [comment]
@Technoblazed thanks! When creating a match, with the bo1/3/5 options, is there any way we can add our own option in there? Say "Arms Race" and have it execute a config. Or is it just modify the existing listings?

Since this is adding a line, how would I in the web select the "somecfgname" option I've declared? Or am I literally just describing what I should see? Hah!

**Comment by Technoblazed** [comment]
In the example I provided you would be setting a definitive config file, what you'd need to do to have it configurable would be to fork get5-web itself and modify the application to suit your needs.

**Comment by BloodyIron** [comment]
@Technoblazed I just want to make sure I understand accurately. When I define that config, it is the same config that will executed, whether it's bo1/bo3/bo5?

I appreciate you spending the time to clarify this, we're going to be using this very shortly, and I want to make sure I got this straight. :)

**Comment by Technoblazed** [comment]
It will always use the config you specify.

**Comment by BloodyIron** [comment]
@Technoblazed thanks! :) we're using this to manage a bunch of servers at a LAN, so I wasn't sure if I had to declare that on each get5 server, or just in the web one or what.
