### ISSUE TITLE
Default Apache Web Page

### ISSUE THREAD

**Issue by jongod5399** [splewis/get5-web#86]
Hi,

I've installed everything correctly (to my knowledge) following the Installation Guide on Ubuntu Server 17.10 in a VM. No errors, everything went fine. However when I access the web interface of my machine I just get the default /var/www/html/index.html from apache/ubuntu.
I had to run everything from root since there were permission problems everywhere running from standard user. Maybe this is the problem? Or maybe I missed something somewhere in the apache settings?

It's as if the WSGIScriptAlias is not recognized. I restarted the service as indicated but even rebooting the server did not make any progress.

Thanks

**Comment by Technoblazed** [comment]
When I created the install guide, I ran over it multiple times ensuring it was as copy pastable as possible, I'm honestly not entirely sure what to give as advice.

**Comment by jongod5399** [comment]
Running Ubuntu 16.04 did not change anything.
I also tried changing 
```
Order allow,deny
Allow from all
```
to
```
Require all granted
```
as described [here](http://flask.pocoo.org/docs/0.12/deploying/mod_wsgi/) but still no change.

**Comment by Technoblazed** [comment]
Please paste your get5.wsgi and get5.conf

**Comment by jongod5399** [comment]
I finally managed to get it working. I had to diable the default site using `sudo a2dissite 000-default.conf`.
After that, get5 loaded properly. It might be a good idea to add the command in the guide if anybody else run into the same issue.

Thank you very much for your time!
