### ISSUE TITLE
Naming each server's hostname

### ISSUE THREAD

**Issue by BloodyIron** [splewis/get5-web#87]
When using get5-web to manage a bunch of servers, my understanding is that it will execute the config used by get5-web.

Now, I would really like it if I could use get5-web to manage the names of each server, so that at a LAN we can tell which team is on which server, based on the "hostname" parameter sent to the SRCDS server.

However, I can't yet see how I can accomplish this. Is this currently possible?

**Comment by Technoblazed** [comment]
I just created a pull request for this over in the get5 branch (https://github.com/splewis/get5/pull/231) which should technically work, but I'd definitely go and test it first.

**Comment by BloodyIron** [comment]
@Technoblazed gat dang you are some kinda fast.

So, uhh, we want to use this for the LAN _this_ weekend... is that wishful thinking? Or maybe feasible?

Also, when you say you created a pull request for it on the get5 branch, is that the groundwork for this kind of feature? Or can get5-web already do it's side of the hostname setting, or what?

**Comment by Technoblazed** [comment]
get5-web doesn't really have the support for this, but the version that I just pushed adds a convar that will change the server hostname to Team 1 vs Team 2, where the teamnames are the correct names. If you want to compile that version yourself and give it a test, heres the download for the repo: https://github.com/Technoblazed/get5/archive/3bf31b31db670c3a30d47561d0270abfbe24d3d5.zip

**Comment by BloodyIron** [comment]
@Technoblazed so, assuming it _works_, what would the expected behaviour of a bunch of get5 servers be when managed by get5-web? Would they just naturally set the srcds hostname to team1 v team2? If so, that actually would be pretty cool. I mean, it would be nice if we could say, add a prefix before that, but out of the box that's pretty neat!

I appreciate the offer for building it myself, but I'm afraid I'm stretched thin with other parts of getting this event going. Sorry! :(

**Comment by Technoblazed** [comment]
Here's a compile version with the binaries: https://i.tech-no.me/get5-3bf131b.zip | But yes, assuming it works when the server is loaded and the names and what not are set, it will change the hostname automatically.

**Comment by BloodyIron** [comment]
@Technoblazed Sweet! I'll try that out when I get a chance! :D Thanks :)

**Comment by splewis** [comment]
Closing since a get5 cvar is added for this.

**Comment by BloodyIron** [comment]
Can the get5-web manage each get5 server for the cvar?
