### ISSUE TITLE
No way to manage/list spectator(s) for matches

### ISSUE THREAD

**Issue by BloodyIron** [splewis/get5-web#88]
Sure, you can add a spectator to a match, but you can't add multiple spectators, nor can you see who has been added, nor remove them.

It would be nice if we could see this stuff and interact with it. :)

This would be particularly helpful for broadcasting stuff. Also, if we could add spectator info when creating a match, that'd be swell too. :D

**Comment by splewis** [comment]
https://github.com/splewis/get5-web/issues/8

**Comment by BloodyIron** [comment]
oops!
