### ISSUE TITLE
When creating a server, and setting it to public, other admins can't make matches with it

### ISSUE THREAD

**Issue by BloodyIron** [splewis/get5-web#89]
Yeah so I created a bunch of servers with my account, set it public, but my other admins can't use the server for matches. Had to delete and remake the servers under their account.

What's up with that?

**Comment by Technoblazed** [comment]
So when you create the servers and click public server it’s not appearing for them?

**Comment by BloodyIron** [comment]
I create the server, set it public, they can see it when creating a match. However when they try to actually create the match, they are told they aren't allowed to use that server.

To be EXPLICIT though, I created the server first without checking public. THEN edited it and checked public.

**Comment by splewis** [comment]
Thanks - that was a crucial detail. 21f14ccf03198b22ab61daf5a155d75f1c3bb105 should have this fixed.

**Comment by BloodyIron** [comment]
Excellent! I'm glad my pedantry is finally paying off. HAH! :3
