### ISSUE TITLE
BO3 with preset maps

### ISSUE THREAD

**Issue by Dieterfu** [splewis/get5-web#92]
Hello,
is it possible to set the maps which should played in BO3 before the matchs starts without veto in a config or via the webpanel?

Thank you
With best regards
Dieter

**Comment by Technoblazed** [comment]
Change `skip_veto` to true in the match config: https://github.com/splewis/get5/blob/master/configs/get5/example_match.json#L7

Change the maplist array to only be the three maps you want played.

**Comment by splewis** [comment]
Yes. See how skip_veto is documented: https://github.com/splewis/get5#match-schema

You can't do this with the get5-web panel without code changes.
