### ISSUE TITLE
The result and statistics do not change

### ISSUE THREAD

**Issue by toster234** [splewis/get5-web#94]
If i create match and join server, in web panel i see status pending and 0 == 0 do not change.. If match is end It is still on this page 0 == 0.

**Comment by KuzyCS** [comment]
Have you moved the web_stats file from disabled?

**Comment by toster234** [comment]
> Have you moved the web_stats file from disabled?

Yes

**Comment by splewis** [comment]
I don't know what the "web_stats" file is. I assume you mean the get5_apistats plugin.

Can you post error logs/plugin version? https://github.com/splewis/get5/wiki/Debugging-help

**Comment by splewis** [comment]
I'm closing this for now since there's no followup information. Feel free to reopen if you can provide the info I request above.
