### ISSUE TITLE
Some players not coming up on scoreboard AND no public servers and teams box.

### ISSUE THREAD

**Issue by KuzyCS** [splewis/get5-web#95]
Hey I have two issues and can't seem to find answers to the two on the repository.  The two issues are:

**Players not coming up on the scoreboard, but were playing in the match**
Not sure how to describe the issue, best described by using a picture.
![screenshot_4](https://user-images.githubusercontent.com/34557728/38459004-34f27c32-3a9c-11e8-9df0-3c47ab2a1e39.png)

**No public check box**
Even though we are whitlisted as admins on the server (web server), we are not able to check the public box for both teams and servers.

If you could come up with a solution to these problems it would be greatly appreciated.  Thanks in advance, Jac.

**Comment by splewis** [comment]
Can you post error logs/plugin version?

https://github.com/splewis/get5/wiki/Debugging-help

**Comment by splewis** [comment]
I'm going to close this since there's no version info, so it's not actionable. 

Feel free to reopen if you can provide more information. I'm happy to show you how to get it.
